TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install) into <top>/db
# databases, templates, substitutions like this
#DB += iocAdminSoft.db
#DB += save_restoreStatus.db
#DB += bpm.db
#DB += cc.db
#DB += fofb.db
#DB += ActiveInterlock.db
#DB += aie.db
#DB += aie_din.db
#DB += aie_fpga_cal.db
#DB += cc_sdi_pos.db
#DB += bpm_alarm_sumery.db
#DB += bpm_id23_alarm_sum.db
DB += xbpm.db
DB += xbpm_sydor.db
#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_template = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

