#!/bin/bash

: << DESCRIPTION
Generation of Bend PSs IOC start script

DESCRIPTION

numpsc=([0]=01 [1]=02 [2]=03)

PSLIST="BR-PS{PS:BD1} BR-PS{PS:BD2} BR-PS{PS:BF}"

echo '#!../../bin/linux-x86/psc'
echo

echo '< envPaths'
echo

echo 'epicsEnvSet("EPICS_CA_AUTO_ADDR_LIST","NO")'
echo 'epicsEnvSet("EPICS_CA_ADDR_LIST","10.0.153.255")'
echo 'epicsEnvSet("IOCNAME", "ps-br-bend-ng")'
echo

echo "#epicsThreadSleep 5"
echo

echo 'cd ${TOP}'
echo

echo '## Register all support components'
echo 'dbLoadDatabase("dbd/psc.dbd",0,0)'
echo 'psc_registerRecordDeviceDriver(pdbbase)'
echo

echo '## Load record instances'
echo

count=0
while [ $count -le 2 ]
do
  echo
  echo 'dbLoadRecords("db/Commands.db",       "PriSys=BR, PS=PSC'${numpsc[$count]}'")'
  echo 'dbLoadRecords("db/Status.db",         "PriSys=BR, PS=PSC'${numpsc[$count]}'")'
  echo '# ADC waveforms (both 10k and 1k)'
  echo 'dbLoadRecords("db/ADCWaveform.db",    "PSy=BR, PS=PSC'${numpsc[$count]}', TIMESTAMP=BST-TS{EVR:B1A}Cnt:BRPrev-I, ADC1K_POINTS=1014, ADC10K_POINTS=10150")'
  echo '# adjusted ADC waveforms are below'
  echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:00_Raw-I,  OUTPUT=BR{PSC'${numpsc[$count]}'}ADC:00-I, WF_LENGTH=1014")'
  echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:01_Raw-I,  OUTPUT=BR{PSC'${numpsc[$count]}'}ADC:01-I, WF_LENGTH=1014")'
  echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:02_Raw-I,  OUTPUT=BR{PSC'${numpsc[$count]}'}ADC:02-I, WF_LENGTH=1014")'
  echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:03_Raw-I,  OUTPUT=BR{PSC'${numpsc[$count]}'}ADC:03-I, WF_LENGTH=1014")'
  echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:04_Raw-I,  OUTPUT=BR{PSC'${numpsc[$count]}'}ADC:04-I, WF_LENGTH=1014")'
  echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:05_Raw-I,  OUTPUT=BR{PSC'${numpsc[$count]}'}ADC:05-I, WF_LENGTH=1014")'
  echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:06_Raw-I,  OUTPUT=BR{PSC'${numpsc[$count]}'}ADC:06-I, WF_LENGTH=1014")'
  echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:07_Raw-I,  OUTPUT=BR{PSC'${numpsc[$count]}'}ADC:07-I, WF_LENGTH=1014")'
  echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:08_Raw-I,  OUTPUT=BR{PSC'${numpsc[$count]}'}ADC:08-I, WF_LENGTH=1014")'
  echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:09_Raw-I,  OUTPUT=BR{PSC'${numpsc[$count]}'}ADC:09-I, WF_LENGTH=1014")'
  echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:10_Raw-I,  OUTPUT=BR{PSC'${numpsc[$count]}'}ADC:10-I, WF_LENGTH=1014")'
  echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:11_Raw-I,  OUTPUT=BR{PSC'${numpsc[$count]}'}ADC:11-I, WF_LENGTH=1014")'
  echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:12_Raw-I,  OUTPUT=BR{PSC'${numpsc[$count]}'}ADC:12-I, WF_LENGTH=1014")'
  echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:13_Raw-I,  OUTPUT=BR{PSC'${numpsc[$count]}'}ADC:13-I, WF_LENGTH=1014")'
  echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:14_Raw-I,  OUTPUT=BR{PSC'${numpsc[$count]}'}ADC:14-I, WF_LENGTH=1014")'
  echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:15_Raw-I,  OUTPUT=BR{PSC'${numpsc[$count]}'}ADC:15-I, WF_LENGTH=1014")'
  echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:16_Raw-I,  OUTPUT=BR{PSC'${numpsc[$count]}'}ADC:16-I, WF_LENGTH=1014")'
  echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:17_Raw-I,  OUTPUT=BR{PSC'${numpsc[$count]}'}ADC:17-I, WF_LENGTH=1014")'
  echo
  echo 'dbLoadRecords("db/Average.db",        "INPUT=BR{PSC'${numpsc[$count]}'}ADC10k:0_Raw-I,  OUTPUT=BR{PSC'${numpsc[$count]}'}ADC10k:0-I, WF_LENGTH=10150")'
  echo 'dbLoadRecords("db/Average.db",        "INPUT=BR{PSC'${numpsc[$count]}'}ADC10k:1_Raw-I,  OUTPUT=BR{PSC'${numpsc[$count]}'}ADC10k:1-I, WF_LENGTH=10150")'
  echo 'dbLoadRecords("db/Subtract.db",       "INPUT1=BR{PSC'${numpsc[$count]}'}ADC10k:0-I, INPUT2=BR{PSC'${numpsc[$count]}'}ADC10k:1-I, OUTPUT=BR{PSC'${numpsc[$count]}'}ADC10k_Sub-I, WF_LENGTH=10150")'
  echo 'dbLoadRecords("db/FFT.db",            "INPUT=BR{PSC'${numpsc[$count]}'}ADC10k:0_Raw-I,  OUTPUT=BR{PSC'${numpsc[$count]}'}ADC10k:0_Raw_I_FFT-I, WF_LENGTH=10150")'
  echo 'dbLoadRecords("db/FFT.db",            "INPUT=BR{PSC'${numpsc[$count]}'}ADC10k:1_Raw-I,  OUTPUT=BR{PSC'${numpsc[$count]}'}ADC10k:1_Raw_I_FFT-I, WF_LENGTH=10150")'
  
  echo
  echo 'dbLoadRecords("db/RampingTable.db",   "PriSys=BR, PSC=PSC'${numpsc[$count]}', RAWDATA_LENGTH=43440, WF10K_LENGTH=10150, CHANNEL=0, MSGID=81, DELTA=BR-PS{}Bend_Delta-SP, DELTA_STEPS=BR-PS{}Bend_DeltaSteps-SP")'
  echo 'dbLoadRecords("db/Ch-WfOut-Coeff.db", "INPUT=BR{PSC'${numpsc[$count]}'}DAC:0-SP,         OUTPUT=BR{PSC'${numpsc[$count]}'}DAC:0_Raw-SP,       WF_LENGTH=10150")'
  echo 'dbLoadRecords("db/Subsampling.db",    "INPUT=BR{PSC'${numpsc[$count]}'}DAC:0_Raw-SP,     OUTPUT=BR{PSC'${numpsc[$count]}'}DAC:0_Raw-SP-1k,    WF_LENGTH=10150, WF_LENGTH2=1014, DIVIDER=10")'
  echo 'dbLoadRecords("db/Subsampling.db",    "INPUT=BR{PSC'${numpsc[$count]}'}DAC:0_Raw_tr-SP,  OUTPUT=BR{PSC'${numpsc[$count]}'}DAC:0_Raw_tr-SP-1k, WF_LENGTH=10150, WF_LENGTH2=1014, DIVIDER=10")'
  echo
  echo 'dbLoadRecords("db/RampingTable.db",   "PriSys=BR, PSC=PSC'${numpsc[$count]}', RAWDATA_LENGTH=43440, WF10K_LENGTH=10150, CHANNEL=1, MSGID=82, DELTA=BR-PS{}Bend_Delta-SP, DELTA_STEPS=BR-PS{}Bend_DeltaSteps-SP")'
  echo 'dbLoadRecords("db/Ch-WfOut-Coeff.db", "INPUT=BR{PSC'${numpsc[$count]}'}DAC:1-SP,         OUTPUT=BR{PSC'${numpsc[$count]}'}DAC:1_Raw-SP,       WF_LENGTH=10150")'
  echo 'dbLoadRecords("db/Subsampling.db",    "INPUT=BR{PSC'${numpsc[$count]}'}DAC:1_Raw-SP,     OUTPUT=BR{PSC'${numpsc[$count]}'}DAC:1_Raw-SP-1k,    WF_LENGTH=10150, WF_LENGTH2=1014, DIVIDER=10")'
  echo 'dbLoadRecords("db/Subsampling.db",    "INPUT=BR{PSC'${numpsc[$count]}'}DAC:1_Raw_tr-SP,  OUTPUT=BR{PSC'${numpsc[$count]}'}DAC:1_Raw_tr-SP-1k, WF_LENGTH=10150, WF_LENGTH2=1014, DIVIDER=10")'
  count=$(( $count + 1 ))
done

count=0
for arg in $PSLIST
do
    echo
    echo '# '$arg' Power Supply begins here'
    echo 'dbLoadRecords("db/Ch-WfOut-Coeff.db", "INPUT='$arg'I-SP,              OUTPUT=BR{PSC'${numpsc[$count]}'}DAC:0-SP,    WF_LENGTH=10150")'
    echo
    echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:01-I,          OUTPUT='$arg'I_Raw-I,         WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:16-I,          OUTPUT='$arg'I:DCCT2_Raw-I,   WF_LENGTH=1014")'
    echo
    echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:02-I,          OUTPUT='$arg'I:Err_Raw-I,     WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:03-I,          OUTPUT='$arg'E:PSout_Raw-I,   WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:04-I,          OUTPUT='$arg'I:GND_Raw-I,     WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:05-I,          OUTPUT='$arg'E:BankH_Raw-I,   WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:06-I,          OUTPUT='$arg'I:BankH_Raw-I,   WF_LENGTH=1014")'
    echo
    echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:09-I,          OUTPUT='$arg'I:DAC_Raw-I,     WF_LENGTH=1014")'
    if [ "$count" -ne 2 ];
    then
     echo
     echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:10-I,          OUTPUT='$arg'E:BankL_Raw-I,   WF_LENGTH=1014")'
     echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:11-I,          OUTPUT='$arg'I:BankL_Raw-I,   WF_LENGTH=1014")'
    fi
    echo
    echo 'dbLoadRecords("db/Ch-DOut.db",        "INPUT='$arg'Cmd:PwrOn-Cmd,     OUTPUT=BR{PSC'${numpsc[$count]}'}DO:0-Cmd")'
    echo 'dbLoadRecords("db/Ch-DOut.db",        "INPUT='$arg'Cmd:PwrOff-Cmd,    OUTPUT=BR{PSC'${numpsc[$count]}'}DO:1-Cmd")'
    echo 'dbLoadRecords("db/Ch-DOut.db",        "INPUT='$arg'Cmd:RstErr-Cmd,    OUTPUT=BR{PSC'${numpsc[$count]}'}DO:3-Cmd")'
    echo
    echo 'dbLoadRecords("db/Ch-DIn.db",         "INPUT=BR{PSC'${numpsc[$count]}'}DI:00-Sts,         OUTPUT='$arg'Flt:DCCT-Sts")'
    echo 'dbLoadRecords("db/Ch-DIn.db",         "INPUT=BR{PSC'${numpsc[$count]}'}DI:01-Sts,         OUTPUT='$arg'Flt:IGBT-Sts")'
    echo 'dbLoadRecords("db/Ch-DIn.db",         "INPUT=BR{PSC'${numpsc[$count]}'}DI:02-Sts,         OUTPUT='$arg'Flt:AcPhase-Sts")'
    echo 'dbLoadRecords("db/Ch-DIn.db",         "INPUT=BR{PSC'${numpsc[$count]}'}DI:03-Sts,         OUTPUT='$arg'Flt:PSwater-Sts")'
    echo 'dbLoadRecords("db/Ch-DIn.db",         "INPUT=BR{PSC'${numpsc[$count]}'}DI:04-Sts,         OUTPUT='$arg'Flt:PSovrcurr-Sts")'
    echo 'dbLoadRecords("db/Ch-DIn.db",         "INPUT=BR{PSC'${numpsc[$count]}'}DI:05-Sts,         OUTPUT='$arg'Flt:Regulator-Sts")'
    echo 'dbLoadRecords("db/Ch-DIn.db",         "INPUT=BR{PSC'${numpsc[$count]}'}DI:06-Sts,         OUTPUT='$arg'Sts:CircBreaker-Sts")'
    echo 'dbLoadRecords("db/Ch-DIn.db",         "INPUT=BR{PSC'${numpsc[$count]}'}DI:07-Sts,         OUTPUT='$arg'Flt:PSovrheat-Sts")'
    echo 'dbLoadRecords("db/Ch-DIn.db",         "INPUT=BR{PSC'${numpsc[$count]}'}DI:08-Sts,         OUTPUT='$arg'Flt:Loadovrheat-Sts")'
    echo 'dbLoadRecords("db/Ch-DIn.db",         "INPUT=BR{PSC'${numpsc[$count]}'}DI:09-Sts,         OUTPUT='$arg'Flt:BankFuse-Sts")'
    echo 'dbLoadRecords("db/Ch-DIn.db",         "INPUT=BR{PSC'${numpsc[$count]}'}DI:10-Sts,         OUTPUT='$arg'Sts:RmtCtrl-Sts")'
    echo 'dbLoadRecords("db/Ch-DIn.db",         "INPUT=BR{PSC'${numpsc[$count]}'}DI:11-Sts,         OUTPUT='$arg'Sts:Rdy-Sts")'
    echo 'dbLoadRecords("db/Ch-DIn.db",         "INPUT=BR{PSC'${numpsc[$count]}'}DI:12-Sts,         OUTPUT='$arg'Flt:GNDleak-Sts")'
    echo 'dbLoadRecords("db/Ch-DIn.db",         "INPUT=BR{PSC'${numpsc[$count]}'}DI:13-Sts,         OUTPUT='$arg'Flt:DoorEmergButt-Sts")'
    echo 'dbLoadRecords("db/Ch-DIn.db",         "INPUT=BR{PSC'${numpsc[$count]}'}DI:14-Sts,         OUTPUT='$arg'Sts:SumInterlock-Sts")'
    echo 'dbLoadRecords("db/Ch-DIn.db",         "INPUT=BR{PSC'${numpsc[$count]}'}DI:15-Sts,         OUTPUT='$arg'Sts:PwrOn-Sts")'
    echo
    echo 'dbLoadRecords("db/Subsampling.db",    "INPUT='$arg'I-SP,      OUTPUT='$arg'I_Raw-SP-1k, WF_LENGTH=10150, WF_LENGTH2=1014, DIVIDER=10")'
    echo
    echo 'dbLoadRecords("db/Average.db",        "INPUT='$arg'I_Raw-SP-1k,   OUTPUT='$arg'I-SP-1k, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'I-SP-1k,       INDEX='$arg'I-SP-1k-Slicer-Idx1, OUTPUT='$arg'I-SP-1k-Slicer-Val1, DOL=, OMSL=supervisory, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'I-SP-1k,       INDEX='$arg'I-SP-1k-Slicer-Idx2, OUTPUT='$arg'I-SP-1k-Slicer-Val2, DOL=, OMSL=supervisory, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'I-SP-1k,       INDEX='$arg'I-SP-1k-Slicer-Idx3, OUTPUT='$arg'I-SP-1k-Slicer-Val3, DOL=, OMSL=supervisory, WF_LENGTH=1014")'
    echo
    echo 'dbLoadRecords("db/Average.db",        "INPUT='$arg'I_Raw-I,   OUTPUT='$arg'I-I, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'I-I,       INDEX='$arg'I-I-Slicer-Idx1, OUTPUT='$arg'I-I-Slicer-Val1, DOL=, OMSL=supervisory, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'I-I,       INDEX='$arg'I-I-Slicer-Idx2, OUTPUT='$arg'I-I-Slicer-Val2, DOL=, OMSL=supervisory, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'I-I,       INDEX='$arg'I-I-Slicer-Idx3, OUTPUT='$arg'I-I-Slicer-Val3, DOL=, OMSL=supervisory, WF_LENGTH=1014")'
    echo
    echo 'dbLoadRecords("db/Average.db",        "INPUT='$arg'I:DCCT2_Raw-I, OUTPUT='$arg'I:DCCT2-I, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'I:DCCT2-I,     INDEX='$arg'I:DCCT2-I-Slicer-Idx1, OUTPUT='$arg'I:DCCT2-I-Slicer-Val1, DOL=, OMSL=supervisory, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'I:DCCT2-I,     INDEX='$arg'I:DCCT2-I-Slicer-Idx2, OUTPUT='$arg'I:DCCT2-I-Slicer-Val2, DOL=, OMSL=supervisory, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'I:DCCT2-I,     INDEX='$arg'I:DCCT2-I-Slicer-Idx3, OUTPUT='$arg'I:DCCT2-I-Slicer-Val3, DOL=, OMSL=supervisory, WF_LENGTH=1014")'
    echo
    echo 'dbLoadRecords("db/Average.db",        "INPUT='$arg'I:Err_Raw-I,   OUTPUT='$arg'I:Err-I, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'I:Err-I,       INDEX='$arg'I:Err-I-Slicer-Idx1, OUTPUT='$arg'I:Err-I-Slicer-Val1, DOL=, OMSL=supervisory, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'I:Err-I,       INDEX='$arg'I:Err-I-Slicer-Idx2, OUTPUT='$arg'I:Err-I-Slicer-Val2, DOL=, OMSL=supervisory, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'I:Err-I,       INDEX='$arg'I:Err-I-Slicer-Idx3, OUTPUT='$arg'I:Err-I-Slicer-Val3, DOL=, OMSL=supervisory, WF_LENGTH=1014")'
    echo
    echo 'dbLoadRecords("db/Average.db",        "INPUT='$arg'E:PSout_Raw-I,   OUTPUT='$arg'E:PSout-I, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'E:PSout-I,       INDEX='$arg'E:PSout-I-Slicer-Idx1, OUTPUT='$arg'E:PSout-I-Slicer-Val1, DOL=, OMSL=supervisory, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'E:PSout-I,       INDEX='$arg'E:PSout-I-Slicer-Idx2, OUTPUT='$arg'E:PSout-I-Slicer-Val2, DOL=, OMSL=supervisory, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'E:PSout-I,       INDEX='$arg'E:PSout-I-Slicer-Idx3, OUTPUT='$arg'E:PSout-I-Slicer-Val3, DOL=, OMSL=supervisory, WF_LENGTH=1014")'
    echo
    echo 'dbLoadRecords("db/Average.db",        "INPUT='$arg'I:GND_Raw-I,   OUTPUT='$arg'I:GND-I, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'I:GND-I,       INDEX='$arg'I:GND-I-Slicer-Idx1, OUTPUT='$arg'I:GND-I-Slicer-Val1, DOL=, OMSL=supervisory, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'I:GND-I,       INDEX='$arg'I:GND-I-Slicer-Idx2, OUTPUT='$arg'I:GND-I-Slicer-Val2, DOL=, OMSL=supervisory, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'I:GND-I,       INDEX='$arg'I:GND-I-Slicer-Idx3, OUTPUT='$arg'I:GND-I-Slicer-Val3, DOL=, OMSL=supervisory, WF_LENGTH=1014")'
    echo
    echo 'dbLoadRecords("db/Average.db",        "INPUT='$arg'E:BankH_Raw-I,   OUTPUT='$arg'E:BankH-I, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'E:BankH-I,       INDEX='$arg'E:BankH-I-Slicer-Idx1, OUTPUT='$arg'E:BankH-I-Slicer-Val1, DOL=, OMSL=supervisory, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'E:BankH-I,       INDEX='$arg'E:BankH-I-Slicer-Idx2, OUTPUT='$arg'E:BankH-I-Slicer-Val2, DOL=, OMSL=supervisory, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'E:BankH-I,       INDEX='$arg'E:BankH-I-Slicer-Idx3, OUTPUT='$arg'E:BankH-I-Slicer-Val3, DOL=, OMSL=supervisory, WF_LENGTH=1014")'
    echo
    echo 'dbLoadRecords("db/Average.db",        "INPUT='$arg'I:BankH_Raw-I,   OUTPUT='$arg'I:BankH-I, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'I:BankH-I,       INDEX='$arg'I:BankH-I-Slicer-Idx1, OUTPUT='$arg'I:BankH-I-Slicer-Val1, DOL=, OMSL=supervisory, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'I:BankH-I,       INDEX='$arg'I:BankH-I-Slicer-Idx2, OUTPUT='$arg'I:BankH-I-Slicer-Val2, DOL=, OMSL=supervisory, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'I:BankH-I,       INDEX='$arg'I:BankH-I-Slicer-Idx3, OUTPUT='$arg'I:BankH-I-Slicer-Val3, DOL=, OMSL=supervisory, WF_LENGTH=1014")'
    echo
    echo 'dbLoadRecords("db/Average.db",        "INPUT='$arg'I:DAC_Raw-I,   OUTPUT='$arg'I:DAC-I, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'I:DAC-I,       INDEX='$arg'I:DAC-I-Slicer-Idx1, OUTPUT='$arg'I:DAC-I-Slicer-Val1, DOL=, OMSL=supervisory, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'I:DAC-I,       INDEX='$arg'I:DAC-I-Slicer-Idx2, OUTPUT='$arg'I:DAC-I-Slicer-Val2, DOL=, OMSL=supervisory, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'I:DAC-I,       INDEX='$arg'I:DAC-I-Slicer-Idx3, OUTPUT='$arg'I:DAC-I-Slicer-Val3, DOL=, OMSL=supervisory, WF_LENGTH=1014")'


    if [ "$count" -ne 2 ];
    then
     echo
     echo 'dbLoadRecords("db/Average.db",        "INPUT='$arg'E:BankL_Raw-I,   OUTPUT='$arg'E:BankL-I, WF_LENGTH=1014")'
     echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'E:BankL-I,       INDEX='$arg'E:BankL-I-Slicer-Idx1, OUTPUT='$arg'E:BankL-I-Slicer-Val1, DOL=, OMSL=supervisory, WF_LENGTH=1014")'
     echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'E:BankL-I,       INDEX='$arg'E:BankL-I-Slicer-Idx2, OUTPUT='$arg'E:BankL-I-Slicer-Val2, DOL=, OMSL=supervisory, WF_LENGTH=1014")'
     echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'E:BankL-I,       INDEX='$arg'E:BankL-I-Slicer-Idx3, OUTPUT='$arg'E:BankL-I-Slicer-Val3, DOL=, OMSL=supervisory, WF_LENGTH=1014")'
     echo
     echo 'dbLoadRecords("db/Average.db",        "INPUT='$arg'I:BankL_Raw-I,   OUTPUT='$arg'I:BankL-I, WF_LENGTH=1014")'
     echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'I:BankL-I,       INDEX='$arg'I:BankL-I-Slicer-Idx1, OUTPUT='$arg'I:BankL-I-Slicer-Val1, DOL=, OMSL=supervisory, WF_LENGTH=1014")'
     echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'I:BankL-I,       INDEX='$arg'I:BankL-I-Slicer-Idx2, OUTPUT='$arg'I:BankL-I-Slicer-Val2, DOL=, OMSL=supervisory, WF_LENGTH=1014")'
     echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'I:BankL-I,       INDEX='$arg'I:BankL-I-Slicer-Idx3, OUTPUT='$arg'I:BankL-I-Slicer-Val3, DOL=, OMSL=supervisory, WF_LENGTH=1014")'
    fi

    echo
    echo 'dbLoadRecords("db/MonitWfCommon.db", "CH='$arg'I-SP, CH_REF='$arg'I-SP_Ref, CH_TOL='$arg'I_SP_Tol-SP, CH_ARCH='$arg'I_SP_Arch-I, CH_DIFFREF='$arg'I_SP_DiffRef-I, CH_DIFFARCH='$arg'I_SP_DiffArch-I, CH_FLG='$arg'I_SP_MonitFlg-Sts, CH_FLGARCH='$arg'I_SP_ArchFlg-Sts, CH_COEFF='$arg'I_SP_MonitCoeff-SP, MODE_PV=BR{}MonitMode-Sel, DATA_TYPE=FLOAT, WF_LENGTH=10150")'
    echo 'dbLoadRecords("db/MonitWf.db",  "CH='$arg'I-SP, CH_REF='$arg'I-SP_Ref, CH_DIFFREF='$arg'I_SP_DiffRef-I, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'I_SP_MonitFlg-Sts, MODE=2, ENABLED=1, DATA_TYPE=FLOAT, WF_LENGTH=10150")'
    echo 'dbLoadRecords("db/MonitWf.db",  "CH='$arg'I-SP, CH_REF='$arg'I-SP_Ref, CH_DIFFREF='$arg'I_SP_DiffRef-I, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'I_SP_MonitFlg-Sts, MODE=1, ENABLED=0, DATA_TYPE=FLOAT, WF_LENGTH=10150")'    
    echo
    echo 'dbLoadRecords("db/MonitWfCommon.db", "CH='$arg'I-I, CH_REF='$arg'I-I_Ref, CH_TOL='$arg'I_I_Tol-SP, CH_ARCH='$arg'I_I_Arch-I, CH_DIFFREF='$arg'I_I_DiffRef-I, CH_DIFFARCH='$arg'I_I_DiffArch-I, CH_FLG='$arg'I_I_MonitFlg-Sts, CH_FLGARCH='$arg'I_I_ArchFlg-Sts, CH_COEFF='$arg'I_I_MonitCoeff-SP, MODE_PV=BR{}MonitMode-Sel, DATA_TYPE=FLOAT, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/MonitWf.db",  "CH='$arg'I-I, CH_REF='$arg'I-I_Ref, CH_DIFFREF='$arg'I_I_DiffRef-I, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'I_I_MonitFlg-Sts, MODE=2, ENABLED=1, DATA_TYPE=FLOAT, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/MonitWf.db",  "CH='$arg'I-I, CH_REF='$arg'I-SP-1k, CH_DIFFREF='$arg'I_I_DiffRef-I, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'I_I_MonitFlg-Sts, MODE=1, ENABLED=1, DATA_TYPE=FLOAT, WF_LENGTH=1014")'
    echo 
    echo 'dbLoadRecords("db/MonitWfCommon.db", "CH='$arg'I:DCCT2-I, CH_REF='$arg'I:DCCT2-I_Ref, CH_TOL='$arg'I:DCCT2_I_Tol-SP, CH_ARCH='$arg'I:DCCT2_I_Arch-I, CH_DIFFREF='$arg'I:DCCT2_I_DiffRef-I, CH_DIFFARCH='$arg'I:DCCT2_I_DiffArch-I, CH_FLG='$arg'I:DCCT2_I_MonitFlg-Sts, CH_FLGARCH='$arg'I:DCCT2_I_ArchFlg-Sts, CH_COEFF='$arg'I:DCCT2_I_MonitCoeff-SP, MODE_PV=BR{}MonitMode-Sel, DATA_TYPE=FLOAT, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/MonitWf.db",  "CH='$arg'I:DCCT2-I, CH_REF='$arg'I:DCCT2-I_Ref, CH_DIFFREF='$arg'I:DCCT2_I_DiffRef-I, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'I:DCCT2_I_MonitFlg-Sts, MODE=2, ENABLED=1, DATA_TYPE=FLOAT, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/MonitWf.db",  "CH='$arg'I:DCCT2-I, CH_REF='$arg'I-SP-1k, CH_DIFFREF='$arg'I:DCCT2_I_DiffRef-I, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'I:DCCT2_I_MonitFlg-Sts, MODE=1, ENABLED=1, DATA_TYPE=FLOAT, WF_LENGTH=1014")'
    echo 
    echo 'dbLoadRecords("db/MonitWfCommon.db", "CH='$arg'I:Err-I, CH_REF='$arg'I:Err-I_Ref, CH_TOL='$arg'I:Err_I_Tol-SP, CH_ARCH='$arg'I:Err_I_Arch-I, CH_DIFFREF='$arg'I:Err_I_DiffRef-I, CH_DIFFARCH='$arg'I:Err_I_DiffArch-I, CH_FLG='$arg'I:Err_I_MonitFlg-Sts, CH_FLGARCH='$arg'I:Err_I_ArchFlg-Sts, CH_COEFF='$arg'I:Err_I_MonitCoeff-SP, MODE_PV=BR{}MonitMode-Sel, DATA_TYPE=FLOAT, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/MonitWf.db",  "CH='$arg'I:Err-I, CH_REF='$arg'I:Err-I_Ref, CH_DIFFREF='$arg'I:Err_I_DiffRef-I, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'I:Err_I_MonitFlg-Sts, MODE=2, ENABLED=1, DATA_TYPE=FLOAT, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/MonitWf.db",  "CH='$arg'I:Err-I, CH_REF='$arg'I:Err-I_Ref, CH_DIFFREF='$arg'I:Err_I_DiffRef-I, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'I:Err_I_MonitFlg-Sts, MODE=1, ENABLED=0, DATA_TYPE=FLOAT, WF_LENGTH=1014")'    
    echo 
    echo 'dbLoadRecords("db/MonitWfCommon.db", "CH='$arg'E:PSout-I, CH_REF='$arg'E:PSout-I_Ref, CH_TOL='$arg'E:PSout_I_Tol-SP, CH_ARCH='$arg'E:PSout_I_Arch-I, CH_DIFFREF='$arg'E:PSout_I_DiffRef-I, CH_DIFFARCH='$arg'E:PSout_I_DiffArch-I, CH_FLG='$arg'E:PSout_I_MonitFlg-Sts, CH_FLGARCH='$arg'E:PSout_I_ArchFlg-Sts, CH_COEFF='$arg'E:PSout_I_MonitCoeff-SP, MODE_PV=BR{}MonitMode-Sel, DATA_TYPE=FLOAT, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/MonitWf.db",  "CH='$arg'E:PSout-I, CH_REF='$arg'E:PSout-I_Ref, CH_DIFFREF='$arg'E:PSout_I_DiffRef-I, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'E:PSout_I_MonitFlg-Sts, MODE=2, ENABLED=1, DATA_TYPE=FLOAT, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/MonitWf.db",  "CH='$arg'E:PSout-I, CH_REF='$arg'E:PSout-I_Ref, CH_DIFFREF='$arg'E:PSout_I_DiffRef-I, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'E:PSout_I_MonitFlg-Sts, MODE=1, ENABLED=0, DATA_TYPE=FLOAT, WF_LENGTH=1014")'    
    echo 
    echo 'dbLoadRecords("db/MonitWfCommon.db", "CH='$arg'I:GND-I, CH_REF='$arg'I:GND-I_Ref, CH_TOL='$arg'I:GND_I_Tol-SP, CH_ARCH='$arg'I:GND_I_Arch-I, CH_DIFFREF='$arg'I:GND_I_DiffRef-I, CH_DIFFARCH='$arg'I:GND_I_DiffArch-I, CH_FLG='$arg'I:GND_I_MonitFlg-Sts, CH_FLGARCH='$arg'I:GND_I_ArchFlg-Sts, CH_COEFF='$arg'I:GND_I_MonitCoeff-SP, MODE_PV=BR{}MonitMode-Sel, DATA_TYPE=FLOAT, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/MonitWf.db",  "CH='$arg'I:GND-I, CH_REF='$arg'I:GND-I_Ref, CH_DIFFREF='$arg'I:GND_I_DiffRef-I, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'I:GND_I_MonitFlg-Sts, MODE=2, ENABLED=1, DATA_TYPE=FLOAT, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/MonitWf.db",  "CH='$arg'I:GND-I, CH_REF='$arg'I:GND-I_Ref, CH_DIFFREF='$arg'I:GND_I_DiffRef-I, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'I:GND_I_MonitFlg-Sts, MODE=1, ENABLED=0, DATA_TYPE=FLOAT, WF_LENGTH=1014")'    
    echo 
    echo 'dbLoadRecords("db/MonitWfCommon.db", "CH='$arg'E:BankH-I, CH_REF='$arg'E:BankH-I_Ref, CH_TOL='$arg'E:BankH_I_Tol-SP, CH_ARCH='$arg'E:BankH_I_Arch-I, CH_DIFFREF='$arg'E:BankH_I_DiffRef-I, CH_DIFFARCH='$arg'E:BankH_I_DiffArch-I, CH_FLG='$arg'E:BankH_I_MonitFlg-Sts, CH_FLGARCH='$arg'E:BankH_I_ArchFlg-Sts, CH_COEFF='$arg'E:BankH_I_MonitCoeff-SP, MODE_PV=BR{}MonitMode-Sel, DATA_TYPE=FLOAT, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/MonitWf.db",  "CH='$arg'E:BankH-I, CH_REF='$arg'E:BankH-I_Ref, CH_DIFFREF='$arg'E:BankH_I_DiffRef-I, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'E:BankH_I_MonitFlg-Sts, MODE=2, ENABLED=1, DATA_TYPE=FLOAT, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/MonitWf.db",  "CH='$arg'E:BankH-I, CH_REF='$arg'E:BankH-I_Ref, CH_DIFFREF='$arg'E:BankH_I_DiffRef-I, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'E:BankH_I_MonitFlg-Sts, MODE=1, ENABLED=0, DATA_TYPE=FLOAT, WF_LENGTH=1014")'    
    echo 
    echo 'dbLoadRecords("db/MonitWfCommon.db", "CH='$arg'I:BankH-I, CH_REF='$arg'I:BankH-I_Ref, CH_TOL='$arg'I:BankH_I_Tol-SP, CH_ARCH='$arg'I:BankH_I_Arch-I, CH_DIFFREF='$arg'I:BankH_I_DiffRef-I, CH_DIFFARCH='$arg'I:BankH_I_DiffArch-I, CH_FLG='$arg'I:BankH_I_MonitFlg-Sts, CH_FLGARCH='$arg'I:BankH_I_ArchFlg-Sts, CH_COEFF='$arg'I:BankH_I_MonitCoeff-SP, MODE_PV=BR{}MonitMode-Sel, DATA_TYPE=FLOAT, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/MonitWf.db",  "CH='$arg'I:BankH-I, CH_REF='$arg'I:BankH-I_Ref, CH_DIFFREF='$arg'I:BankH_I_DiffRef-I, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'I:BankH_I_MonitFlg-Sts, MODE=2, ENABLED=1, DATA_TYPE=FLOAT, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/MonitWf.db",  "CH='$arg'I:BankH-I, CH_REF='$arg'I:BankH-I_Ref, CH_DIFFREF='$arg'I:BankH_I_DiffRef-I, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'I:BankH_I_MonitFlg-Sts, MODE=1, ENABLED=0, DATA_TYPE=FLOAT, WF_LENGTH=1014")'    
    echo 
    echo 'dbLoadRecords("db/MonitWfCommon.db", "CH='$arg'I:DAC-I, CH_REF='$arg'I:DAC-I_Ref, CH_TOL='$arg'I:DAC_I_Tol-SP,  CH_ARCH='$arg'I:DAC_I_Arch-I, CH_DIFFREF='$arg'I:DAC_I_DiffRef-I, CH_DIFFARCH='$arg'I:DAC_I_DiffArch-I, CH_FLG='$arg'I:DAC_I_MonitFlg-Sts, CH_FLGARCH='$arg'I:DAC_I_ArchFlg-Sts, CH_COEFF='$arg'I:DAC_I_MonitCoeff-SP, MODE_PV=BR{}MonitMode-Sel, DATA_TYPE=FLOAT, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/MonitWf.db",  "CH='$arg'I:DAC-I, CH_REF='$arg'I:DAC-I_Ref, CH_DIFFREF='$arg'I:DAC_I_DiffRef-I, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'I:DAC_I_MonitFlg-Sts, MODE=2, ENABLED=1, DATA_TYPE=FLOAT, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/MonitWf.db",  "CH='$arg'I:DAC-I, CH_REF='$arg'I-SP-1k, CH_DIFFREF='$arg'I:DAC_I_DiffRef-I, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'I:DAC_I_MonitFlg-Sts, MODE=1, ENABLED=1, DATA_TYPE=FLOAT, WF_LENGTH=1014")'
    echo     
   if [ "$count" -ne 2 ];
    then
    echo 'dbLoadRecords("db/MonitWfCommon.db", "CH='$arg'E:BankL-I, CH_REF='$arg'E:BankL-I_Ref, CH_TOL='$arg'E:BankL_I_Tol-SP, CH_ARCH='$arg'E:BankL_I_Arch-I, CH_DIFFREF='$arg'E:BankL_I_DiffRef-I, CH_DIFFARCH='$arg'E:BankL_I_DiffArch-I, CH_FLG='$arg'E:BankL_I_MonitFlg-Sts, CH_FLGARCH='$arg'E:BankL_I_ArchFlg-Sts, CH_COEFF='$arg'E:BankL_I_MonitCoeff-SP, MODE_PV=BR{}MonitMode-Sel, DATA_TYPE=FLOAT, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/MonitWf.db",  "CH='$arg'E:BankL-I, CH_REF='$arg'E:BankL-I_Ref, CH_DIFFREF='$arg'E:BankL_I_DiffRef-I, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'E:BankL_I_MonitFlg-Sts, MODE=2, ENABLED=1, DATA_TYPE=FLOAT, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/MonitWf.db",  "CH='$arg'E:BankL-I, CH_REF='$arg'E:BankL-I_Ref, CH_DIFFREF='$arg'E:BankL_I_DiffRef-I, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'E:BankL_I_MonitFlg-Sts, MODE=1, ENABLED=0, DATA_TYPE=FLOAT, WF_LENGTH=1014")'    
    echo 
    echo 'dbLoadRecords("db/MonitWfCommon.db", "CH='$arg'I:BankL-I, CH_REF='$arg'I:BankL-I_Ref, CH_TOL='$arg'I:BankL_I_Tol-SP, CH_ARCH='$arg'I:BankL_I_Arch-I, CH_DIFFREF='$arg'I:BankL_I_DiffRef-I, CH_DIFFARCH='$arg'I:BankL_I_DiffArch-I, CH_FLG='$arg'I:BankL_I_MonitFlg-Sts, CH_FLGARCH='$arg'I:BankL_I_ArchFlg-Sts, CH_COEFF='$arg'I:BankL_I_MonitCoeff-SP, MODE_PV=BR{}MonitMode-Sel, DATA_TYPE=FLOAT, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/MonitWf.db",  "CH='$arg'I:BankL-I, CH_REF='$arg'I:BankL-I_Ref, CH_DIFFREF='$arg'I:BankL_I_DiffRef-I, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'I:BankL_I_MonitFlg-Sts, MODE=2, ENABLED=1, DATA_TYPE=FLOAT, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/MonitWf.db",  "CH='$arg'I:BankL-I, CH_REF='$arg'I:BankL-I_Ref, CH_DIFFREF='$arg'I:BankL_I_DiffRef-I, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'I:BankL_I_MonitFlg-Sts, MODE=1, ENABLED=0, DATA_TYPE=FLOAT, WF_LENGTH=1014")'    
    echo
   fi


    echo 'dbLoadRecords("db/MonitBinaryCommon.db", "CH='$arg'Cmd:PwrOn-Cmd, CH_REF='$arg'Cmd:PwrOn-Cmd_Ref, CH_ARCH='$arg'Cmd:PwrOn_Arch-Sts, CH_FLG='$arg'Cmd:PwrOn_MonitFlg-Sts, CH_FLGARCH='$arg'Cmd:PwrOn_ArchFlg-Sts, MODE_PV=BR{}MonitMode-Sel")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Cmd:PwrOn-Cmd, CH_REF='$arg'Cmd:PwrOn-Cmd_Ref, CH_FLG='$arg'Cmd:PwrOn_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Cmd:PwrOn_MonitFlg-Sts, MODE=2, ENABLED=1")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Cmd:PwrOn-Cmd, CH_REF='$arg'Cmd:PwrOn-Cmd_Ref, CH_FLG='$arg'Cmd:PwrOn_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Cmd:PwrOn_MonitFlg-Sts, MODE=1, ENABLED=0")'    
    echo 
    echo 'dbLoadRecords("db/MonitBinaryCommon.db", "CH='$arg'Cmd:PwrOff-Cmd, CH_REF='$arg'Cmd:PwrOff-Cmd_Ref, CH_ARCH='$arg'Cmd:PwrOff_Arch-Sts, CH_FLG='$arg'Cmd:PwrOff_MonitFlg-Sts, CH_FLGARCH='$arg'Cmd:PwrOff_ArchFlg-Sts, MODE_PV=BR{}MonitMode-Sel")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Cmd:PwrOff-Cmd, CH_REF='$arg'Cmd:PwrOff-Cmd_Ref, CH_FLG='$arg'Cmd:PwrOff_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Cmd:PwrOff_MonitFlg-Sts, MODE=2, ENABLED=1")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Cmd:PwrOff-Cmd, CH_REF='$arg'Cmd:PwrOff-Cmd_Ref, CH_FLG='$arg'Cmd:PwrOff_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Cmd:PwrOff_MonitFlg-Sts, MODE=1, ENABLED=0")'    
    echo 
    echo 'dbLoadRecords("db/MonitBinaryCommon.db", "CH='$arg'Cmd:RstErr-Cmd, CH_REF='$arg'Cmd:RstErr-Cmd_Ref, CH_ARCH='$arg'Cmd:RstErr_Arch-Sts, CH_FLG='$arg'Cmd:RstErr_MonitFlg-Sts, CH_FLGARCH='$arg'Cmd:RstErr_ArchFlg-Sts, MODE_PV=BR{}MonitMode-Sel")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Cmd:RstErr-Cmd, CH_REF='$arg'Cmd:RstErr-Cmd_Ref, CH_FLG='$arg'Cmd:RstErr_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Cmd:RstErr_MonitFlg-Sts, MODE=2, ENABLED=1")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Cmd:RstErr-Cmd, CH_REF='$arg'Cmd:RstErr-Cmd_Ref, CH_FLG='$arg'Cmd:RstErr_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Cmd:RstErr_MonitFlg-Sts, MODE=1, ENABLED=0")'    
    echo 

    echo 'dbLoadRecords("db/MonitBinaryCommon.db", "CH='$arg'Flt:DCCT-Sts, CH_REF='$arg'Flt:DCCT-Sts_Ref, CH_ARCH='$arg'Flt:DCCT_Arch-Sts, CH_FLG='$arg'Flt:DCCT_MonitFlg-Sts, CH_FLGARCH='$arg'Flt:DCCT_ArchFlg-Sts, MODE_PV=BR{}MonitMode-Sel")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Flt:DCCT-Sts, CH_REF='$arg'Flt:DCCT-Sts_Ref, CH_FLG='$arg'Flt:DCCT_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Flt:DCCT_MonitFlg-Sts, MODE=2, ENABLED=1")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Flt:DCCT-Sts, CH_REF='$arg'Flt:DCCT-Sts_Ref, CH_FLG='$arg'Flt:DCCT_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Flt:DCCT_MonitFlg-Sts, MODE=1, ENABLED=0")'    
    echo 
    echo 'dbLoadRecords("db/MonitBinaryCommon.db", "CH='$arg'Flt:IGBT-Sts, CH_REF='$arg'Flt:IGBT-Sts_Ref, CH_ARCH='$arg'Flt:IGBT_Arch-Sts, CH_FLG='$arg'Flt:IGBT_MonitFlg-Sts, CH_FLGARCH='$arg'Flt:IGBT_ArchFlg-Sts, MODE_PV=BR{}MonitMode-Sel")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Flt:IGBT-Sts, CH_REF='$arg'Flt:IGBT-Sts_Ref, CH_FLG='$arg'Flt:IGBT_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Flt:IGBT_MonitFlg-Sts, MODE=2, ENABLED=1")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Flt:IGBT-Sts, CH_REF='$arg'Flt:IGBT-Sts_Ref, CH_FLG='$arg'Flt:IGBT_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Flt:IGBT_MonitFlg-Sts, MODE=1, ENABLED=0")'    
    echo 
    echo 'dbLoadRecords("db/MonitBinaryCommon.db", "CH='$arg'Flt:AcPhase-Sts, CH_REF='$arg'Flt:AcPhase-Sts_Ref, CH_ARCH='$arg'Flt:AcPhase_Arch-Sts, CH_FLG='$arg'Flt:AcPhase_MonitFlg-Sts, CH_FLGARCH='$arg'Flt:AcPhase_ArchFlg-Sts, MODE_PV=BR{}MonitMode-Sel")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Flt:AcPhase-Sts, CH_REF='$arg'Flt:AcPhase-Sts_Ref, CH_FLG='$arg'Flt:AcPhase_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Flt:AcPhase_MonitFlg-Sts, MODE=2, ENABLED=1")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Flt:AcPhase-Sts, CH_REF='$arg'Flt:AcPhase-Sts_Ref, CH_FLG='$arg'Flt:AcPhase_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Flt:AcPhase_MonitFlg-Sts, MODE=1, ENABLED=0")'    
    echo 
    echo 'dbLoadRecords("db/MonitBinaryCommon.db", "CH='$arg'Flt:PSwater-Sts, CH_REF='$arg'Flt:PSwater-Sts_Ref, CH_ARCH='$arg'Flt:PSwater_Arch-Sts, CH_FLG='$arg'Flt:PSwater_MonitFlg-Sts, CH_FLGARCH='$arg'Flt:PSwater_ArchFlg-Sts, MODE_PV=BR{}MonitMode-Sel")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Flt:PSwater-Sts, CH_REF='$arg'Flt:PSwater-Sts_Ref, CH_FLG='$arg'Flt:PSwater_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Flt:PSwater_MonitFlg-Sts, MODE=2, ENABLED=1")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Flt:PSwater-Sts, CH_REF='$arg'Flt:PSwater-Sts_Ref, CH_FLG='$arg'Flt:PSwater_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Flt:PSwater_MonitFlg-Sts, MODE=1, ENABLED=0")'    
    echo 
    echo 'dbLoadRecords("db/MonitBinaryCommon.db", "CH='$arg'Flt:PSovrcurr-Sts, CH_REF='$arg'Flt:PSovrcurr-Sts_Ref, CH_ARCH='$arg'Flt:PSovrcurr_Arch-Sts, CH_FLG='$arg'Flt:PSovrcurr_MonitFlg-Sts, CH_FLGARCH='$arg'Flt:PSovrcurr_ArchFlg-Sts, MODE_PV=BR{}MonitMode-Sel")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Flt:PSovrcurr-Sts, CH_REF='$arg'Flt:PSovrcurr-Sts_Ref, CH_FLG='$arg'Flt:PSovrcurr_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Flt:PSovrcurr_MonitFlg-Sts, MODE=2, ENABLED=1")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Flt:PSovrcurr-Sts, CH_REF='$arg'Flt:PSovrcurr-Sts_Ref, CH_FLG='$arg'Flt:PSovrcurr_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Flt:PSovrcurr_MonitFlg-Sts, MODE=1, ENABLED=0")'    
    echo 
    echo 'dbLoadRecords("db/MonitBinaryCommon.db", "CH='$arg'Flt:Regulator-Sts, CH_REF='$arg'Flt:Regulator-Sts_Ref, CH_ARCH='$arg'Flt:Regulator_Arch-Sts, CH_FLG='$arg'Flt:Regulator_MonitFlg-Sts, CH_FLGARCH='$arg'Flt:Regulator_ArchFlg-Sts, MODE_PV=BR{}MonitMode-Sel")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Flt:Regulator-Sts, CH_REF='$arg'Flt:Regulator-Sts_Ref, CH_FLG='$arg'Flt:Regulator_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Flt:Regulator_MonitFlg-Sts, MODE=2, ENABLED=1")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Flt:Regulator-Sts, CH_REF='$arg'Flt:Regulator-Sts_Ref, CH_FLG='$arg'Flt:Regulator_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Flt:Regulator_MonitFlg-Sts, MODE=1, ENABLED=0")'    
    echo 
    echo 'dbLoadRecords("db/MonitBinaryCommon.db", "CH='$arg'Sts:CircBreaker-Sts, CH_REF='$arg'Sts:CircBreaker-Sts_Ref, CH_ARCH='$arg'Sts:CircBreaker_Arch-Sts, CH_FLG='$arg'Sts:CircBreaker_MonitFlg-Sts, CH_FLGARCH='$arg'Sts:CircBreaker_ArchFlg-Sts, MODE_PV=BR{}MonitMode-Sel")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Sts:CircBreaker-Sts, CH_REF='$arg'Sts:CircBreaker-Sts_Ref, CH_FLG='$arg'Sts:CircBreaker_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Sts:CircBreaker_MonitFlg-Sts, MODE=2, ENABLED=1")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Sts:CircBreaker-Sts, CH_REF='$arg'Sts:CircBreaker-Sts_Ref, CH_FLG='$arg'Sts:CircBreaker_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Sts:CircBreaker_MonitFlg-Sts, MODE=1, ENABLED=0")'    
    echo 
    echo 'dbLoadRecords("db/MonitBinaryCommon.db", "CH='$arg'Flt:PSovrheat-Sts, CH_REF='$arg'Flt:PSovrheat-Sts_Ref, CH_ARCH='$arg'Flt:PSovrheat_Arch-Sts, CH_FLG='$arg'Flt:PSovrheat_MonitFlg-Sts, CH_FLGARCH='$arg'Flt:PSovrheat_ArchFlg-Sts, MODE_PV=BR{}MonitMode-Sel")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Flt:PSovrheat-Sts, CH_REF='$arg'Flt:PSovrheat-Sts_Ref, CH_FLG='$arg'Flt:PSovrheat_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Flt:PSovrheat_MonitFlg-Sts, MODE=2, ENABLED=1")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Flt:PSovrheat-Sts, CH_REF='$arg'Flt:PSovrheat-Sts_Ref, CH_FLG='$arg'Flt:PSovrheat_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Flt:PSovrheat_MonitFlg-Sts, MODE=1, ENABLED=0")'    
    echo 
    echo 'dbLoadRecords("db/MonitBinaryCommon.db", "CH='$arg'Flt:Loadovrheat-Sts, CH_REF='$arg'Flt:Loadovrheat-Sts_Ref, CH_ARCH='$arg'Flt:Loadovrheat_Arch-Sts, CH_FLG='$arg'Flt:Loadovrheat_MonitFlg-Sts, CH_FLGARCH='$arg'Flt:Loadovrheat_ArchFlg-Sts, MODE_PV=BR{}MonitMode-Sel")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Flt:Loadovrheat-Sts, CH_REF='$arg'Flt:Loadovrheat-Sts_Ref, CH_FLG='$arg'Flt:Loadovrheat_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Flt:Loadovrheat_MonitFlg-Sts, MODE=2, ENABLED=1")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Flt:Loadovrheat-Sts, CH_REF='$arg'Flt:Loadovrheat-Sts_Ref, CH_FLG='$arg'Flt:Loadovrheat_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Flt:Loadovrheat_MonitFlg-Sts, MODE=1, ENABLED=0")'    
    echo 
    echo 'dbLoadRecords("db/MonitBinaryCommon.db", "CH='$arg'Flt:BankFuse-Sts, CH_REF='$arg'Flt:BankFuse-Sts_Ref, CH_ARCH='$arg'Flt:BankFuse_Arch-Sts, CH_FLG='$arg'Flt:BankFuse_MonitFlg-Sts, CH_FLGARCH='$arg'Flt:BankFuse_ArchFlg-Sts, MODE_PV=BR{}MonitMode-Sel")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Flt:BankFuse-Sts, CH_REF='$arg'Flt:BankFuse-Sts_Ref, CH_FLG='$arg'Flt:BankFuse_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Flt:BankFuse_MonitFlg-Sts, MODE=2, ENABLED=1")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Flt:BankFuse-Sts, CH_REF='$arg'Flt:BankFuse-Sts_Ref, CH_FLG='$arg'Flt:BankFuse_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Flt:BankFuse_MonitFlg-Sts, MODE=1, ENABLED=0")'    
    echo 
    echo 'dbLoadRecords("db/MonitBinaryCommon.db", "CH='$arg'Sts:RmtCtrl-Sts, CH_REF='$arg'Sts:RmtCtrl-Sts_Ref, CH_ARCH='$arg'Sts:RmtCtrl_Arch-Sts, CH_FLG='$arg'Sts:RmtCtrl_MonitFlg-Sts, CH_FLGARCH='$arg'Sts:RmtCtrl_ArchFlg-Sts, MODE_PV=BR{}MonitMode-Sel")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Sts:RmtCtrl-Sts, CH_REF='$arg'Sts:RmtCtrl-Sts_Ref, CH_FLG='$arg'Sts:RmtCtrl_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Sts:RmtCtrl_MonitFlg-Sts, MODE=2, ENABLED=1")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Sts:RmtCtrl-Sts, CH_REF='$arg'Sts:RmtCtrl-Sts_Ref, CH_FLG='$arg'Sts:RmtCtrl_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Sts:RmtCtrl_MonitFlg-Sts, MODE=1, ENABLED=0")'    
    echo 
    echo 'dbLoadRecords("db/MonitBinaryCommon.db", "CH='$arg'Sts:Rdy-Sts, CH_REF='$arg'Sts:Rdy-Sts_Ref, CH_ARCH='$arg'Sts:Rdy_Arch-Sts, CH_FLG='$arg'Sts:Rdy_MonitFlg-Sts, CH_FLGARCH='$arg'Sts:Rdy_ArchFlg-Sts, MODE_PV=BR{}MonitMode-Sel")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Sts:Rdy-Sts, CH_REF='$arg'Sts:Rdy-Sts_Ref, CH_FLG='$arg'Sts:Rdy_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Sts:Rdy_MonitFlg-Sts, MODE=2, ENABLED=1")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Sts:Rdy-Sts, CH_REF='$arg'Sts:Rdy-Sts_Ref, CH_FLG='$arg'Sts:Rdy_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Sts:Rdy_MonitFlg-Sts, MODE=1, ENABLED=0")'    
    echo 
    echo 'dbLoadRecords("db/MonitBinaryCommon.db", "CH='$arg'Flt:GNDleak-Sts, CH_REF='$arg'Flt:GNDleak-Sts_Ref, CH_ARCH='$arg'Flt:GNDleak_Arch-Sts, CH_FLG='$arg'Flt:GNDleak_MonitFlg-Sts, CH_FLGARCH='$arg'Flt:GNDleak_ArchFlg-Sts, MODE_PV=BR{}MonitMode-Sel")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Flt:GNDleak-Sts, CH_REF='$arg'Flt:GNDleak-Sts_Ref, CH_FLG='$arg'Flt:GNDleak_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Flt:GNDleak_MonitFlg-Sts, MODE=2, ENABLED=1")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Flt:GNDleak-Sts, CH_REF='$arg'Flt:GNDleak-Sts_Ref, CH_FLG='$arg'Flt:GNDleak_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Flt:GNDleak_MonitFlg-Sts, MODE=1, ENABLED=0")'    
    echo 
    echo 'dbLoadRecords("db/MonitBinaryCommon.db", "CH='$arg'Flt:DoorEmergButt-Sts, CH_REF='$arg'Flt:DoorEmergButt-Sts_Ref, CH_ARCH='$arg'Flt:DoorEmergButt_Arch-Sts, CH_FLG='$arg'Flt:DoorEmergButt_MonitFlg-Sts, CH_FLGARCH='$arg'Flt:DoorEmergButt_ArchFlg-Sts, MODE_PV=BR{}MonitMode-Sel")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Flt:DoorEmergButt-Sts, CH_REF='$arg'Flt:DoorEmergButt-Sts_Ref, CH_FLG='$arg'Flt:DoorEmergButt_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Flt:DoorEmergButt_MonitFlg-Sts, MODE=2, ENABLED=1")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Flt:DoorEmergButt-Sts, CH_REF='$arg'Flt:DoorEmergButt-Sts_Ref, CH_FLG='$arg'Flt:DoorEmergButt_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Flt:DoorEmergButt_MonitFlg-Sts, MODE=1, ENABLED=0")'    
    echo
    echo 'dbLoadRecords("db/MonitBinaryCommon.db", "CH='$arg'Sts:SumInterlock-Sts, CH_REF='$arg'Sts:SumInterlock-Sts_Ref, CH_ARCH='$arg'Sts:SumInterlock_Arch-Sts, CH_FLG='$arg'Sts:SumInterlock_MonitFlg-Sts, CH_FLGARCH='$arg'Sts:SumInterlock_ArchFlg-Sts, MODE_PV=BR{}MonitMode-Sel")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Sts:SumInterlock-Sts, CH_REF='$arg'Sts:SumInterlock-Sts_Ref, CH_FLG='$arg'Sts:SumInterlock_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Sts:SumInterlock_MonitFlg-Sts, MODE=2, ENABLED=1")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Sts:SumInterlock-Sts, CH_REF='$arg'Sts:SumInterlock-Sts_Ref, CH_FLG='$arg'Sts:SumInterlock_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Sts:SumInterlock_MonitFlg-Sts, MODE=1, ENABLED=0")'    
    echo
    echo 'dbLoadRecords("db/MonitBinaryCommon.db", "CH='$arg'Sts:PwrOn-Sts, CH_REF='$arg'Sts:PwrOn-Sts_Ref, CH_ARCH='$arg'Sts:PwrOn_Arch-Sts, CH_FLG='$arg'Sts:PwrOn_MonitFlg-Sts, CH_FLGARCH='$arg'Sts:PwrOn_ArchFlg-Sts, MODE_PV=BR{}MonitMode-Sel")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Sts:PwrOn-Sts, CH_REF='$arg'Sts:PwrOn-Sts_Ref, CH_FLG='$arg'Sts:PwrOn_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Sts:PwrOn_MonitFlg-Sts, MODE=2, ENABLED=1")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Sts:PwrOn-Sts, CH_REF='$arg'Sts:PwrOn-Sts_Ref, CH_FLG='$arg'Sts:PwrOn_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Sts:PwrOn_MonitFlg-Sts, MODE=1, ENABLED=0")'    
    echo

    count=$(( $count + 1 ))
done 

echo
echo 'var(PSCDebug, 1)'
echo '#with debug message: var(PSCDebug, 2)'

count=0
while [ $count -le 2 ]
do
  echo
  echo '#Tx socket'
  echo 'createPSC("TxPSC'${numpsc[$count]}'", "br-psc'${numpsc[$count]}'", 7, 0)'
  echo 'epicsThreadSleep 0.1'
  echo '#Tx sim socket'
  echo '#createPSC("TxPSC'${numpsc[$count]}'", "localhost", 8765, 0)'
  echo '#Rx socket'
  echo 'createPSC("RxPSC'${numpsc[$count]}'", "br-psc'${numpsc[$count]}'", 20, 1)'
  echo 'epicsThreadSleep 0.1'
  echo 'setPSCSendBlockSize("TxPSC'${numpsc[$count]}'", 80, 128)'
  count=$(( $count + 1 ))
done

echo
echo '### Misc stuff ###'
echo 'epicsEnvSet("LOCATION","740 ISB RGB 1")'
echo 'dbLoadRecords("db/iocAdminSoft.db", "IOC=BR-CT{IOC:${IOCNAME}}")'
echo 'asSetFilename("/cf-update/acf/default.acf")'

echo
echo '### Save/Restore ###'
echo 'dbLoadRecords("db/save_restoreStatus.db", "P=BR-CT{IOC:${IOCNAME}}")'
echo 'save_restoreSet_status_prefix("BR-CT{IOC:${IOCNAME}}")'
echo 'set_savefile_path("${TOP}/../${IOCNAME}","/as/save")'
echo 'set_requestfile_path("${TOP}/../${IOCNAME}","/as/req")'
echo 'set_pass0_restoreFile("${IOCNAME}.sav")'
echo 'set_pass1_restoreFile("${IOCNAME}_waveforms.sav")'

echo
echo '### Start IOC ###'
echo 'cd ${TOP}/iocBoot/${IOC}'
echo 'iocInit()'
echo
echo '### caPutLog ###'
echo 'caPutLogInit("ioclog.cs.nsls2.local:7004", 1)'
echo
echo '### Channel Finder'
echo 'dbl > ${TOP}/../${IOCNAME}/records.dbl'
echo 'system "cp ${TOP}/../${IOCNAME}/records.dbl /cf-update/${HOSTNAME}.${IOCNAME}.dbl"'
echo
echo '### Save/Restore ###'
echo 'makeAutosaveFileFromDbInfo("${TOP}/../${IOCNAME}/as/req/${IOCNAME}.req", "autosaveFields_pass0")'
echo 'makeAutosaveFileFromDbInfo("${TOP}/../${IOCNAME}/as/req/${IOCNAME}_waveforms.req", "autosaveFields_pass1")'

echo
echo 'create_monitor_set("${IOCNAME}.req", 5 , "")'
echo 'create_monitor_set("${IOCNAME}_waveforms.req", 30 , "")'
echo
