#!/bin/bash

: << DESCRIPTION
Generation of Kicker PSs IOC start script

DESCRIPTION

numpsc=([0]=07 [1]=08 [2]=09 [3]=10 [4]=11 [5]=12)

PSLIST="BR:IS-PS{PS:KIC1} BR:IS-PS{PS:KIC2} BR:IS-PS{PS:KIC3} BR:IS-PS{PS:KIC4} BR:XS-PS{PS:KIC1} BR:XS-PS{PS:KIC2}"

echo '#!../../bin/linux-x86/psc'
echo

echo '< envPaths'
echo

echo 'epicsEnvSet("EPICS_CA_AUTO_ADDR_LIST","NO")'
echo 'epicsEnvSet("EPICS_CA_ADDR_LIST","10.0.153.255")'
echo 'epicsEnvSet("IOCNAME", "ps-br-kicker-ng")'
echo

echo '# to avoid a lot of "scanOnce: Ring buffer overflow" during save/restore initialization'
echo 'scanOnceSetQueueSize(2000)'
echo

echo "#epicsThreadSleep 5"
echo

echo 'cd ${TOP}'
echo

echo '## Register all support components'
echo 'dbLoadDatabase("dbd/psc.dbd",0,0)'
echo 'psc_registerRecordDeviceDriver(pdbbase)'
echo

echo '## Load record instances'
echo

count=0
while [ $count -le 5 ]
do
  echo
  echo 'dbLoadRecords("db/Commands.db",       "PriSys=BR, PS=PSC'${numpsc[$count]}'")'
  echo 'dbLoadRecords("db/Status.db",         "PriSys=BR, PS=PSC'${numpsc[$count]}'")'
  echo '# ADC waveforms (both 10k and 1k)'
  echo 'dbLoadRecords("db/ADCWaveform.db",    "PSy=BR, PS=PSC'${numpsc[$count]}', TIMESTAMP=BST-TS{EVR:B1A}Cnt:BRPrev-I, ADC1K_POINTS=1014, ADC10K_POINTS=10150")'
  echo '# adjusted ADC waveforms are below'
  echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:00_Raw-I,  OUTPUT=BR{PSC'${numpsc[$count]}'}ADC:00-I, WF_LENGTH=1014")'
  echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:01_Raw-I,  OUTPUT=BR{PSC'${numpsc[$count]}'}ADC:01-I, WF_LENGTH=1014")'
  echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:02_Raw-I,  OUTPUT=BR{PSC'${numpsc[$count]}'}ADC:02-I, WF_LENGTH=1014")'
  echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:03_Raw-I,  OUTPUT=BR{PSC'${numpsc[$count]}'}ADC:03-I, WF_LENGTH=1014")'
  echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:04_Raw-I,  OUTPUT=BR{PSC'${numpsc[$count]}'}ADC:04-I, WF_LENGTH=1014")'
  echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:05_Raw-I,  OUTPUT=BR{PSC'${numpsc[$count]}'}ADC:05-I, WF_LENGTH=1014")'
  echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:06_Raw-I,  OUTPUT=BR{PSC'${numpsc[$count]}'}ADC:06-I, WF_LENGTH=1014")'
  echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:07_Raw-I,  OUTPUT=BR{PSC'${numpsc[$count]}'}ADC:07-I, WF_LENGTH=1014")'
  echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:08_Raw-I,  OUTPUT=BR{PSC'${numpsc[$count]}'}ADC:08-I, WF_LENGTH=1014")'
  echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:09_Raw-I,  OUTPUT=BR{PSC'${numpsc[$count]}'}ADC:09-I, WF_LENGTH=1014")'
  echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:10_Raw-I,  OUTPUT=BR{PSC'${numpsc[$count]}'}ADC:10-I, WF_LENGTH=1014")'
  echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:11_Raw-I,  OUTPUT=BR{PSC'${numpsc[$count]}'}ADC:11-I, WF_LENGTH=1014")'
  echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:12_Raw-I,  OUTPUT=BR{PSC'${numpsc[$count]}'}ADC:12-I, WF_LENGTH=1014")'
  echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:13_Raw-I,  OUTPUT=BR{PSC'${numpsc[$count]}'}ADC:13-I, WF_LENGTH=1014")'
  echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:14_Raw-I,  OUTPUT=BR{PSC'${numpsc[$count]}'}ADC:14-I, WF_LENGTH=1014")'
  echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:15_Raw-I,  OUTPUT=BR{PSC'${numpsc[$count]}'}ADC:15-I, WF_LENGTH=1014")'
  echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:16_Raw-I,  OUTPUT=BR{PSC'${numpsc[$count]}'}ADC:16-I, WF_LENGTH=1014")'
  echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:17_Raw-I,  OUTPUT=BR{PSC'${numpsc[$count]}'}ADC:17-I, WF_LENGTH=1014")'
  echo
  echo 'dbLoadRecords("db/Average.db",        "INPUT=BR{PSC'${numpsc[$count]}'}ADC10k:0_Raw-I,  OUTPUT=BR{PSC'${numpsc[$count]}'}ADC10k:0-I, WF_LENGTH=10150")'
  echo 'dbLoadRecords("db/Average.db",        "INPUT=BR{PSC'${numpsc[$count]}'}ADC10k:1_Raw-I,  OUTPUT=BR{PSC'${numpsc[$count]}'}ADC10k:1-I, WF_LENGTH=10150")'
  echo 'dbLoadRecords("db/Subtract.db",       "INPUT1=BR{PSC'${numpsc[$count]}'}ADC10k:0-I, INPUT2=BR{PSC'${numpsc[$count]}'}ADC10k:1-I, OUTPUT=BR{PSC'${numpsc[$count]}'}ADC10k_Sub-I, WF_LENGTH=10150")'
  echo 'dbLoadRecords("db/FFT.db",            "INPUT=BR{PSC'${numpsc[$count]}'}ADC10k:0_Raw-I,  OUTPUT=BR{PSC'${numpsc[$count]}'}ADC10k:0_Raw_I_FFT-I, WF_LENGTH=10150")'
  echo 'dbLoadRecords("db/FFT.db",            "INPUT=BR{PSC'${numpsc[$count]}'}ADC10k:1_Raw-I,  OUTPUT=BR{PSC'${numpsc[$count]}'}ADC10k:1_Raw_I_FFT-I, WF_LENGTH=10150")'
  
  echo
  echo 'dbLoadRecords("db/RampingTable.db",   "PriSys=BR, PSC=PSC'${numpsc[$count]}', RAWDATA_LENGTH=43440, WF10K_LENGTH=10150, CHANNEL=0, MSGID=81, DELTA=BR-PS{}KIC_Delta-SP, DELTA_STEPS=BR-PS{}KIC_DeltaSteps-SP")'
  echo 'dbLoadRecords("db/Ch-WfOut-Coeff.db", "INPUT=BR{PSC'${numpsc[$count]}'}DAC:0-SP,         OUTPUT=BR{PSC'${numpsc[$count]}'}DAC:0_Raw-SP,       WF_LENGTH=10150")'
  echo 'dbLoadRecords("db/Subsampling.db",    "INPUT=BR{PSC'${numpsc[$count]}'}DAC:0_Raw-SP,     OUTPUT=BR{PSC'${numpsc[$count]}'}DAC:0_Raw-SP-1k,    WF_LENGTH=10150, WF_LENGTH2=1014, DIVIDER=10")'
  echo 'dbLoadRecords("db/Subsampling.db",    "INPUT=BR{PSC'${numpsc[$count]}'}DAC:0_Raw_tr-SP,  OUTPUT=BR{PSC'${numpsc[$count]}'}DAC:0_Raw_tr-SP-1k, WF_LENGTH=10150, WF_LENGTH2=1014, DIVIDER=10")'
  echo
  echo 'dbLoadRecords("db/RampingTable.db",   "PriSys=BR, PSC=PSC'${numpsc[$count]}', RAWDATA_LENGTH=43440, WF10K_LENGTH=10150, CHANNEL=1, MSGID=82, DELTA=BR-PS{}KIC_Delta-SP, DELTA_STEPS=BR-PS{}KIC_DeltaSteps-SP")'
  echo 'dbLoadRecords("db/Ch-WfOut-Coeff.db", "INPUT=BR{PSC'${numpsc[$count]}'}DAC:1-SP,         OUTPUT=BR{PSC'${numpsc[$count]}'}DAC:1_Raw-SP,       WF_LENGTH=10150")'
  echo 'dbLoadRecords("db/Subsampling.db",    "INPUT=BR{PSC'${numpsc[$count]}'}DAC:1_Raw-SP,     OUTPUT=BR{PSC'${numpsc[$count]}'}DAC:1_Raw-SP-1k,    WF_LENGTH=10150, WF_LENGTH2=1014, DIVIDER=10")'
  echo 'dbLoadRecords("db/Subsampling.db",    "INPUT=BR{PSC'${numpsc[$count]}'}DAC:1_Raw_tr-SP,  OUTPUT=BR{PSC'${numpsc[$count]}'}DAC:1_Raw_tr-SP-1k, WF_LENGTH=10150, WF_LENGTH2=1014, DIVIDER=10")'
  count=$(( $count + 1 ))
done

count=0
for arg in $PSLIST
do
    echo
    echo '# '$arg' Power Supply begins here'
    echo 'dbLoadRecords("db/Ch-WfOut-Coeff.db", "INPUT='$arg'E:PFN-SP,                              OUTPUT=BR{PSC'${numpsc[$count]}'}DAC:0-SP,    WF_LENGTH=10150")'
    echo
    echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:00-I,          OUTPUT='$arg'E:DAC_Raw-I,             WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:01-I,          OUTPUT='$arg'E:PFN_Raw-I,             WF_LENGTH=1014")'
    echo
    echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:02-I,          OUTPUT='$arg'I:HVPS_Raw-I,            WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:03-I,          OUTPUT='$arg'E:HVPS_Raw-I,            WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:04-I,          OUTPUT='$arg'E:ThyrHeater1_Raw-I,     WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:05-I,          OUTPUT='$arg'E:ThyrHeater2_Raw-I,     WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Ch-WfIn-Coeff.db",  "INPUT=BR{PSC'${numpsc[$count]}'}ADC:06-I,          OUTPUT='$arg'I:ThyrAuxArcCurr_Raw-I,  WF_LENGTH=1014")'
    echo
    echo 'dbLoadRecords("db/Ch-DOut.db",        "INPUT='$arg'Cmd:RstErr-Cmd,                        OUTPUT=BR{PSC'${numpsc[$count]}'}DO:0-Cmd")'
    echo 'dbLoadRecords("db/Ch-DOut.db",        "INPUT='$arg'Cmd:PwrOn-Cmd,                         OUTPUT=BR{PSC'${numpsc[$count]}'}DO:1-Cmd")'
    echo 'dbLoadRecords("db/Ch-DOut.db",        "INPUT='$arg'Cmd:Stdby-Cmd,                         OUTPUT=BR{PSC'${numpsc[$count]}'}DO:2-Cmd")'
    echo
    echo 'dbLoadRecords("db/Ch-DIn.db",         "INPUT=BR{PSC'${numpsc[$count]}'}DI:00-Sts,         OUTPUT='$arg'Sts:Rdy-Sts")'
    echo 'dbLoadRecords("db/Ch-DIn.db",         "INPUT=BR{PSC'${numpsc[$count]}'}DI:01-Sts,         OUTPUT='$arg'Flt:PFNvoltage-Sts")'
    echo 'dbLoadRecords("db/Ch-DIn.db",         "INPUT=BR{PSC'${numpsc[$count]}'}DI:02-Sts,         OUTPUT='$arg'Flt:PSUovrheat-Sts")'
    echo 'dbLoadRecords("db/Ch-DIn.db",         "INPUT=BR{PSC'${numpsc[$count]}'}DI:03-Sts,         OUTPUT='$arg'Sts:PSUcircBreaker-Sts")'
    echo 'dbLoadRecords("db/Ch-DIn.db",         "INPUT=BR{PSC'${numpsc[$count]}'}DI:04-Sts,         OUTPUT='$arg'Flt:HVPSovrcurr-Sts")'
    echo 'dbLoadRecords("db/Ch-DIn.db",         "INPUT=BR{PSC'${numpsc[$count]}'}DI:05-Sts,         OUTPUT='$arg'Sts:TrigUnitRdy-Sts")'
    echo 'dbLoadRecords("db/Ch-DIn.db",         "INPUT=BR{PSC'${numpsc[$count]}'}DI:06-Sts,         OUTPUT='$arg'Flt:BiasPS-Sts")'
    echo 'dbLoadRecords("db/Ch-DIn.db",         "INPUT=BR{PSC'${numpsc[$count]}'}DI:07-Sts,         OUTPUT='$arg'Sts:PSUcontactor-Sts")'
#    echo 'dbLoadRecords("db/Ch-DIn.db",         "INPUT=BR{PSC'${numpsc[$count]}'}DI:08-Sts,         OUTPUT='$arg'Sts:RackDoor-Sts")'
    echo 'dbLoadRecords("db/Ch-DIn.db",         "INPUT=BR{PSC'${numpsc[$count]}'}DI:09-Sts,         OUTPUT='$arg'Sts:PulserDoors-Sts")'
    echo 'dbLoadRecords("db/Ch-DIn.db",         "INPUT=BR{PSC'${numpsc[$count]}'}DI:10-Sts,         OUTPUT='$arg'Sts:PulserCircBreaker-Sts")'
    echo 'dbLoadRecords("db/Ch-DIn.db",         "INPUT=BR{PSC'${numpsc[$count]}'}DI:11-Sts,         OUTPUT='$arg'Sts:LocalCtrl-Sts")'
    echo 'dbLoadRecords("db/Ch-DIn.db",         "INPUT=BR{PSC'${numpsc[$count]}'}DI:12-Sts,         OUTPUT='$arg'Sts:EmergButton-Sts")'
    echo 'dbLoadRecords("db/Ch-DIn.db",         "INPUT=BR{PSC'${numpsc[$count]}'}DI:13-Sts,         OUTPUT='$arg'Sts:ExtInterlock-Sts")'
    echo 'dbLoadRecords("db/Ch-DIn.db",         "INPUT=BR{PSC'${numpsc[$count]}'}DI:14-Sts,         OUTPUT='$arg'Sts:PulserHVrly-Sts")'
    echo 'dbLoadRecords("db/Ch-DIn.db",         "INPUT=BR{PSC'${numpsc[$count]}'}DI:15-Sts,         OUTPUT='$arg'Flt:HVPSovrvoltage-Sts")'
    echo 
    echo 'dbLoadRecords("db/Subsampling.db",    "INPUT='$arg'E:PFN-SP,              OUTPUT='$arg'E:PFN_Raw-SP-1k, WF_LENGTH=10150, WF_LENGTH2=1014, DIVIDER=10")'
    echo 
    echo 'dbLoadRecords("db/Average.db",        "INPUT='$arg'E:PFN_Raw-SP-1k,       OUTPUT='$arg'E:PFN-SP-1k, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'E:PFN-SP-1k,           INDEX='$arg'E:PFN-SP-1k-Slicer-Idx1, OUTPUT='$arg'E:PFN-SP-1k-Slicer-Val1, DOL=, OMSL=supervisory, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'E:PFN-SP-1k,           INDEX='$arg'E:PFN-SP-1k-Slicer-Idx2, OUTPUT='$arg'E:PFN-SP-1k-Slicer-Val2, DOL=, OMSL=supervisory, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'E:PFN-SP-1k,           INDEX='$arg'E:PFN-SP-1k-Slicer-Idx3, OUTPUT='$arg'E:PFN-SP-1k-Slicer-Val3, DOL=, OMSL=supervisory, WF_LENGTH=1014")'    
    echo 
    echo 'dbLoadRecords("db/Average.db",        "INPUT='$arg'E:DAC_Raw-I,           OUTPUT='$arg'E:DAC-I, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'E:DAC-I,               INDEX='$arg'E:DAC-I-Slicer-Idx1, OUTPUT='$arg'E:DAC-I-Slicer-Val1, DOL=, OMSL=supervisory, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'E:DAC-I,               INDEX='$arg'E:DAC-I-Slicer-Idx2, OUTPUT='$arg'E:DAC-I-Slicer-Val2, DOL=, OMSL=supervisory, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'E:DAC-I,               INDEX='$arg'E:DAC-I-Slicer-Idx3, OUTPUT='$arg'E:DAC-I-Slicer-Val3, DOL=, OMSL=supervisory, WF_LENGTH=1014")'
    echo 
    echo 'dbLoadRecords("db/Average.db",        "INPUT='$arg'E:PFN_Raw-I,           OUTPUT='$arg'E:PFN-I, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'E:PFN-I,               INDEX='$arg'E:PFN-I-Slicer-Idx1, OUTPUT='$arg'E:PFN-I-Slicer-Val1, DOL=, OMSL=supervisory, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'E:PFN-I,               INDEX='$arg'E:PFN-I-Slicer-Idx2, OUTPUT='$arg'E:PFN-I-Slicer-Val2, DOL=, OMSL=supervisory, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'E:PFN-I,               INDEX='$arg'E:PFN-I-Slicer-Idx3, OUTPUT='$arg'E:PFN-I-Slicer-Val3, DOL=, OMSL=supervisory, WF_LENGTH=1014")'    
    echo 
    echo 'dbLoadRecords("db/Average.db",        "INPUT='$arg'I:HVPS_Raw-I,          OUTPUT='$arg'I:HVPS-I, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'I:HVPS-I,              INDEX='$arg'I:HVPS-I-Slicer-Idx1, OUTPUT='$arg'I:HVPS-I-Slicer-Val1, DOL=, OMSL=supervisory, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'I:HVPS-I,              INDEX='$arg'I:HVPS-I-Slicer-Idx2, OUTPUT='$arg'I:HVPS-I-Slicer-Val2, DOL=, OMSL=supervisory, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'I:HVPS-I,              INDEX='$arg'I:HVPS-I-Slicer-Idx3, OUTPUT='$arg'I:HVPS-I-Slicer-Val3, DOL=, OMSL=supervisory, WF_LENGTH=1014")'    
    echo 
    echo 'dbLoadRecords("db/Average.db",        "INPUT='$arg'E:HVPS_Raw-I,          OUTPUT='$arg'E:HVPS-I, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'E:HVPS-I,              INDEX='$arg'E:HVPS-I-Slicer-Idx1, OUTPUT='$arg'E:HVPS-I-Slicer-Val1, DOL=, OMSL=supervisory, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'E:HVPS-I,              INDEX='$arg'E:HVPS-I-Slicer-Idx2, OUTPUT='$arg'E:HVPS-I-Slicer-Val2, DOL=, OMSL=supervisory, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'E:HVPS-I,              INDEX='$arg'E:HVPS-I-Slicer-Idx3, OUTPUT='$arg'E:HVPS-I-Slicer-Val3, DOL=, OMSL=supervisory, WF_LENGTH=1014")'    
    echo
    echo 'dbLoadRecords("db/Average.db",        "INPUT='$arg'E:ThyrHeater1_Raw-I,   OUTPUT='$arg'E:ThyrHeater1-I, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'E:ThyrHeater1-I,       INDEX='$arg'E:ThyrHeater1-I-Slicer-Idx1, OUTPUT='$arg'E:ThyrHeater1-I-Slicer-Val1, DOL=, OMSL=supervisory, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'E:ThyrHeater1-I,       INDEX='$arg'E:ThyrHeater1-I-Slicer-Idx2, OUTPUT='$arg'E:ThyrHeater1-I-Slicer-Val2, DOL=, OMSL=supervisory, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'E:ThyrHeater1-I,       INDEX='$arg'E:ThyrHeater1-I-Slicer-Idx3, OUTPUT='$arg'E:ThyrHeater1-I-Slicer-Val3, DOL=, OMSL=supervisory, WF_LENGTH=1014")'    
    echo 
    echo 'dbLoadRecords("db/Average.db",        "INPUT='$arg'E:ThyrHeater2_Raw-I,   OUTPUT='$arg'E:ThyrHeater2-I, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'E:ThyrHeater2-I,       INDEX='$arg'E:ThyrHeater2-I-Slicer-Idx1, OUTPUT='$arg'E:ThyrHeater2-I-Slicer-Val1, DOL=, OMSL=supervisory, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'E:ThyrHeater2-I,       INDEX='$arg'E:ThyrHeater2-I-Slicer-Idx2, OUTPUT='$arg'E:ThyrHeater2-I-Slicer-Val2, DOL=, OMSL=supervisory, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'E:ThyrHeater2-I,       INDEX='$arg'E:ThyrHeater2-I-Slicer-Idx3, OUTPUT='$arg'E:ThyrHeater2-I-Slicer-Val3, DOL=, OMSL=supervisory, WF_LENGTH=1014")'    
    echo 
    echo 'dbLoadRecords("db/Average.db",        "INPUT='$arg'I:ThyrAuxArcCurr_Raw-I,OUTPUT='$arg'I:ThyrAuxArcCurr-I, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'I:ThyrAuxArcCurr-I,    INDEX='$arg'I:ThyrAuxArcCurr-I-Slicer-Idx1, OUTPUT='$arg'I:ThyrAuxArcCurr-I-Slicer-Val1, DOL=, OMSL=supervisory, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'I:ThyrAuxArcCurr-I,    INDEX='$arg'I:ThyrAuxArcCurr-I-Slicer-Idx2, OUTPUT='$arg'I:ThyrAuxArcCurr-I-Slicer-Val2, DOL=, OMSL=supervisory, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/Slicer2.db",        "INPUT='$arg'I:ThyrAuxArcCurr-I,    INDEX='$arg'I:ThyrAuxArcCurr-I-Slicer-Idx3, OUTPUT='$arg'I:ThyrAuxArcCurr-I-Slicer-Val3, DOL=, OMSL=supervisory, WF_LENGTH=1014")'    
    echo 

    echo 'dbLoadRecords("db/MonitWfCommon.db", "CH='$arg'E:PFN-SP, CH_REF='$arg'E:PFN-SP_Ref, CH_TOL='$arg'E:PFN_SP_Tol-SP, CH_ARCH='$arg'E:PFN_SP_Arch-I, CH_DIFFREF='$arg'E:PFN_SP_DiffRef-I, CH_DIFFARCH='$arg'E:PFN_SP_DiffArch-I, CH_FLG='$arg'E:PFN_SP_MonitFlg-Sts, CH_FLGARCH='$arg'E:PFN_SP_ArchFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_COEFF='$arg'E:PFN_SP_MonitCoeff-SP, DATA_TYPE=FLOAT, WF_LENGTH=10150")'
    echo 'dbLoadRecords("db/MonitWf.db",  "CH='$arg'E:PFN-SP, CH_REF='$arg'E:PFN-SP_Ref, CH_DIFFREF='$arg'E:PFN_SP_DiffRef-I, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'E:PFN_SP_MonitFlg-Sts, MODE=2, ENABLED=1, DATA_TYPE=FLOAT, WF_LENGTH=10150")'
    echo 'dbLoadRecords("db/MonitWf.db",  "CH='$arg'E:PFN-SP, CH_REF='$arg'E:PFN-SP_Ref, CH_DIFFREF='$arg'E:PFN_SP_DiffRef-I, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'E:PFN_SP_MonitFlg-Sts, MODE=1, ENABLED=0, DATA_TYPE=FLOAT, WF_LENGTH=10150")'
    echo

    echo 'dbLoadRecords("db/MonitWfCommon.db", "CH='$arg'E:DAC-I, CH_REF='$arg'E:DAC-I_Ref, CH_TOL='$arg'E:DAC_I_Tol-SP,  CH_ARCH='$arg'E:DAC_I_Arch-I, CH_DIFFREF='$arg'E:DAC_I_DiffRef-I, CH_DIFFARCH='$arg'E:DAC_I_DiffArch-I, CH_FLG='$arg'E:DAC_I_MonitFlg-Sts, CH_FLGARCH='$arg'E:DAC_I_ArchFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_COEFF='$arg'E:DAC_I_MonitCoeff-SP, DATA_TYPE=FLOAT, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/MonitWf.db",  "CH='$arg'E:DAC-I, CH_REF='$arg'E:DAC-I_Ref, CH_DIFFREF='$arg'E:DAC_I_DiffRef-I, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'E:DAC_I_MonitFlg-Sts, MODE=2, ENABLED=1, DATA_TYPE=FLOAT, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/MonitWf.db",  "CH='$arg'E:DAC-I, CH_REF='$arg'E:PFN-SP-1k, CH_DIFFREF='$arg'E:DAC_I_DiffRef-I, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'E:DAC_I_MonitFlg-Sts, MODE=1, ENABLED=1, DATA_TYPE=FLOAT, WF_LENGTH=1014")'
    echo 
    echo 'dbLoadRecords("db/MonitWfCommon.db", "CH='$arg'E:PFN-I, CH_REF='$arg'E:PFN-I_Ref, CH_TOL='$arg'E:PFN_I_Tol-SP, CH_ARCH='$arg'E:PFN_I_Arch-I, CH_DIFFREF='$arg'E:PFN_I_DiffRef-I, CH_DIFFARCH='$arg'E:PFN_I_DiffArch-I, CH_FLG='$arg'E:PFN_I_MonitFlg-Sts, CH_FLGARCH='$arg'E:PFN_I_ArchFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_COEFF='$arg'E:PFN_I_MonitCoeff-SP, DATA_TYPE=FLOAT, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/MonitWf.db",  "CH='$arg'E:PFN-I, CH_REF='$arg'E:PFN-I_Ref, CH_DIFFREF='$arg'E:PFN_I_DiffRef-I, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'E:PFN_I_MonitFlg-Sts, MODE=2, ENABLED=1, DATA_TYPE=FLOAT, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/MonitWf.db",  "CH='$arg'E:PFN-I, CH_REF='$arg'E:PFN-I_Ref, CH_DIFFREF='$arg'E:PFN_I_DiffRef-I, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'E:PFN_I_MonitFlg-Sts, MODE=1, ENABLED=0, DATA_TYPE=FLOAT, WF_LENGTH=1014")'    
    echo 
    echo 'dbLoadRecords("db/MonitWfCommon.db", "CH='$arg'I:HVPS-I, CH_REF='$arg'I:HVPS-I_Ref, CH_TOL='$arg'I:HVPS_I_Tol-SP,  CH_ARCH='$arg'I:HVPS_I_Arch-I, CH_DIFFREF='$arg'I:HVPS_I_DiffRef-I, CH_DIFFARCH='$arg'I:HVPS_I_DiffArch-I, CH_FLG='$arg'I:HVPS_I_MonitFlg-Sts, CH_FLGARCH='$arg'I:HVPS_I_ArchFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_COEFF='$arg'I:HVPS_I_MonitCoeff-SP, DATA_TYPE=FLOAT, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/MonitWf.db",  "CH='$arg'I:HVPS-I, CH_REF='$arg'I:HVPS-I_Ref, CH_DIFFREF='$arg'I:HVPS_I_DiffRef-I, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'I:HVPS_I_MonitFlg-Sts, MODE=2, ENABLED=1, DATA_TYPE=FLOAT, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/MonitWf.db",  "CH='$arg'I:HVPS-I, CH_REF='$arg'I:HVPS-I_Ref, CH_DIFFREF='$arg'I:HVPS_I_DiffRef-I, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'I:HVPS_I_MonitFlg-Sts, MODE=1, ENABLED=0, DATA_TYPE=FLOAT, WF_LENGTH=1014")'    
    echo 
    echo 'dbLoadRecords("db/MonitWfCommon.db", "CH='$arg'E:HVPS-I, CH_REF='$arg'E:HVPS-I_Ref, CH_TOL='$arg'E:HVPS_I_Tol-SP,  CH_ARCH='$arg'E:HVPS_I_Arch-I, CH_DIFFREF='$arg'E:HVPS_I_DiffRef-I, CH_DIFFARCH='$arg'E:HVPS_I_DiffArch-I, CH_FLG='$arg'E:HVPS_I_MonitFlg-Sts, CH_FLGARCH='$arg'E:HVPS_I_ArchFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_COEFF='$arg'E:HVPS_I_MonitCoeff-SP, DATA_TYPE=FLOAT, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/MonitWf.db",  "CH='$arg'E:HVPS-I, CH_REF='$arg'E:HVPS-I_Ref, CH_DIFFREF='$arg'E:HVPS_I_DiffRef-I, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'E:HVPS_I_MonitFlg-Sts, MODE=2, ENABLED=1, DATA_TYPE=FLOAT, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/MonitWf.db",  "CH='$arg'E:HVPS-I, CH_REF='$arg'E:HVPS-I_Ref, CH_DIFFREF='$arg'E:HVPS_I_DiffRef-I, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'E:HVPS_I_MonitFlg-Sts, MODE=1, ENABLED=0, DATA_TYPE=FLOAT, WF_LENGTH=1014")'
    echo 
    echo 'dbLoadRecords("db/MonitWfCommon.db", "CH='$arg'E:ThyrHeater1-I, CH_REF='$arg'E:ThyrHeater1-I_Ref, CH_TOL='$arg'E:ThyrHeater1_I_Tol-SP,  CH_ARCH='$arg'E:ThyrHeater1_I_Arch-I, CH_DIFFREF='$arg'E:ThyrHeater1_I_DiffRef-I, CH_DIFFARCH='$arg'E:ThyrHeater1_I_DiffArch-I, CH_FLG='$arg'E:ThyrHeater1_I_MonitFlg-Sts, CH_FLGARCH='$arg'E:ThyrHeater1_I_ArchFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_COEFF='$arg'E:ThyrHeater1_I_MonitCoeff-SP, DATA_TYPE=FLOAT, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/MonitWf.db",  "CH='$arg'E:ThyrHeater1-I, CH_REF='$arg'E:ThyrHeater1-I_Ref, CH_DIFFREF='$arg'E:ThyrHeater1_I_DiffRef-I, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'E:ThyrHeater1_I_MonitFlg-Sts, MODE=2, ENABLED=1, DATA_TYPE=FLOAT, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/MonitWf.db",  "CH='$arg'E:ThyrHeater1-I, CH_REF='$arg'E:ThyrHeater1-I_Ref, CH_DIFFREF='$arg'E:ThyrHeater1_I_DiffRef-I, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'E:ThyrHeater1_I_MonitFlg-Sts, MODE=1, ENABLED=0, DATA_TYPE=FLOAT, WF_LENGTH=1014")'    
    echo 
    echo 'dbLoadRecords("db/MonitWfCommon.db", "CH='$arg'E:ThyrHeater2-I, CH_REF='$arg'E:ThyrHeater2-I_Ref, CH_TOL='$arg'E:ThyrHeater2_I_Tol-SP,  CH_ARCH='$arg'E:ThyrHeater2_I_Arch-I, CH_DIFFREF='$arg'E:ThyrHeater2_I_DiffRef-I, CH_DIFFARCH='$arg'E:ThyrHeater2_I_DiffArch-I, CH_FLG='$arg'E:ThyrHeater2_I_MonitFlg-Sts, CH_FLGARCH='$arg'E:ThyrHeater2_I_ArchFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_COEFF='$arg'E:ThyrHeater2_I_MonitCoeff-SP, DATA_TYPE=FLOAT, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/MonitWf.db",  "CH='$arg'E:ThyrHeater2-I, CH_REF='$arg'E:ThyrHeater2-I_Ref, CH_DIFFREF='$arg'E:ThyrHeater2_I_DiffRef-I, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'E:ThyrHeater2_I_MonitFlg-Sts, MODE=2, ENABLED=1, DATA_TYPE=FLOAT, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/MonitWf.db",  "CH='$arg'E:ThyrHeater2-I, CH_REF='$arg'E:ThyrHeater2-I_Ref, CH_DIFFREF='$arg'E:ThyrHeater2_I_DiffRef-I, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'E:ThyrHeater2_I_MonitFlg-Sts, MODE=1, ENABLED=0, DATA_TYPE=FLOAT, WF_LENGTH=1014")'
    echo 
    echo 'dbLoadRecords("db/MonitWfCommon.db", "CH='$arg'I:ThyrAuxArcCurr-I, CH_REF='$arg'I:ThyrAuxArcCurr-I_Ref, CH_TOL='$arg'I:ThyrAuxArcCurr_I_Tol-SP,  CH_ARCH='$arg'I:ThyrAuxArcCurr_I_Arch-I, CH_DIFFREF='$arg'I:ThyrAuxArcCurr_I_DiffRef-I, CH_DIFFARCH='$arg'I:ThyrAuxArcCurr_I_DiffArch-I, CH_FLG='$arg'I:ThyrAuxArcCurr_I_MonitFlg-Sts, CH_FLGARCH='$arg'I:ThyrAuxArcCurr_I_ArchFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_COEFF='$arg'I:ThyrAuxArcCurr_I_MonitCoeff-SP, DATA_TYPE=FLOAT, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/MonitWf.db",  "CH='$arg'I:ThyrAuxArcCurr-I, CH_REF='$arg'I:ThyrAuxArcCurr-I_Ref, CH_DIFFREF='$arg'I:ThyrAuxArcCurr_I_DiffRef-I, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'I:ThyrAuxArcCurr_I_MonitFlg-Sts, MODE=2, ENABLED=1, DATA_TYPE=FLOAT, WF_LENGTH=1014")'
    echo 'dbLoadRecords("db/MonitWf.db",  "CH='$arg'I:ThyrAuxArcCurr-I, CH_REF='$arg'I:ThyrAuxArcCurr-I_Ref, CH_DIFFREF='$arg'I:ThyrAuxArcCurr_I_DiffRef-I, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'I:ThyrAuxArcCurr_I_MonitFlg-Sts, MODE=1, ENABLED=0, DATA_TYPE=FLOAT, WF_LENGTH=1014")'
    echo 

    echo 'dbLoadRecords("db/MonitBinaryCommon.db", "CH='$arg'Cmd:RstErr-Cmd, CH_REF='$arg'Cmd:RstErr-Cmd_Ref, CH_ARCH='$arg'Cmd:RstErr_Arch-Sts, CH_FLG='$arg'Cmd:RstErr_MonitFlg-Sts, CH_FLGARCH='$arg'Cmd:RstErr_ArchFlg-Sts, MODE_PV=BR{}MonitMode-Sel")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Cmd:RstErr-Cmd, CH_REF='$arg'Cmd:RstErr-Cmd_Ref, CH_FLG='$arg'Cmd:RstErr_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Cmd:RstErr_MonitFlg-Sts, MODE=2, ENABLED=1")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Cmd:RstErr-Cmd, CH_REF='$arg'Cmd:RstErr-Cmd_Ref, CH_FLG='$arg'Cmd:RstErr_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Cmd:RstErr_MonitFlg-Sts, MODE=1, ENABLED=0")'
    echo
    echo 'dbLoadRecords("db/MonitBinaryCommon.db", "CH='$arg'Cmd:PwrOn-Cmd, CH_REF='$arg'Cmd:PwrOn-Cmd_Ref, CH_ARCH='$arg'Cmd:PwrOn_Arch-Sts, CH_FLG='$arg'Cmd:PwrOn_MonitFlg-Sts, CH_FLGARCH='$arg'Cmd:PwrOn_ArchFlg-Sts, MODE_PV=BR{}MonitMode-Sel")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Cmd:PwrOn-Cmd, CH_REF='$arg'Cmd:PwrOn-Cmd_Ref, CH_FLG='$arg'Cmd:PwrOn_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Cmd:PwrOn_MonitFlg-Sts, MODE=2, ENABLED=1")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Cmd:PwrOn-Cmd, CH_REF='$arg'Cmd:PwrOn-Cmd_Ref, CH_FLG='$arg'Cmd:PwrOn_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Cmd:PwrOn_MonitFlg-Sts, MODE=1, ENABLED=0")'
    echo 
    echo 'dbLoadRecords("db/MonitBinaryCommon.db", "CH='$arg'Cmd:Stdby-Cmd, CH_REF='$arg'Cmd:Stdby-Cmd_Ref, CH_ARCH='$arg'Cmd:Stdby_Arch-Sts, CH_FLG='$arg'Cmd:Stdby_MonitFlg-Sts, CH_FLGARCH='$arg'Cmd:Stdby_ArchFlg-Sts, MODE_PV=BR{}MonitMode-Sel")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Cmd:Stdby-Cmd, CH_REF='$arg'Cmd:Stdby-Cmd_Ref, CH_FLG='$arg'Cmd:Stdby_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Cmd:Stdby_MonitFlg-Sts, MODE=2, ENABLED=1")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Cmd:Stdby-Cmd, CH_REF='$arg'Cmd:Stdby-Cmd_Ref, CH_FLG='$arg'Cmd:Stdby_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Cmd:Stdby_MonitFlg-Sts, MODE=1, ENABLED=0")'
    echo 

    echo 'dbLoadRecords("db/MonitBinaryCommon.db", "CH='$arg'Sts:Rdy-Sts, CH_REF='$arg'Sts:Rdy-Sts_Ref, CH_ARCH='$arg'Sts:Rdy_Arch-Sts, CH_FLG='$arg'Sts:Rdy_MonitFlg-Sts, CH_FLGARCH='$arg'Sts:Rdy_ArchFlg-Sts, MODE_PV=BR{}MonitMode-Sel")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Sts:Rdy-Sts, CH_REF='$arg'Sts:Rdy-Sts_Ref, CH_FLG='$arg'Sts:Rdy_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Sts:Rdy_MonitFlg-Sts, MODE=2, ENABLED=1")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Sts:Rdy-Sts, CH_REF='$arg'Sts:Rdy-Sts_Ref, CH_FLG='$arg'Sts:Rdy_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Sts:Rdy_MonitFlg-Sts, MODE=1, ENABLED=0")'
    echo 
    echo 'dbLoadRecords("db/MonitBinaryCommon.db", "CH='$arg'Flt:PFNvoltage-Sts, CH_REF='$arg'Flt:PFNvoltage-Sts_Ref, CH_ARCH='$arg'Flt:PFNvoltage_Arch-Sts, CH_FLG='$arg'Flt:PFNvoltage_MonitFlg-Sts, CH_FLGARCH='$arg'Flt:PFNvoltage_ArchFlg-Sts, MODE_PV=BR{}MonitMode-Sel")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Flt:PFNvoltage-Sts, CH_REF='$arg'Flt:PFNvoltage-Sts_Ref, CH_FLG='$arg'Flt:PFNvoltage_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Flt:PFNvoltage_MonitFlg-Sts, MODE=2, ENABLED=1")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Flt:PFNvoltage-Sts, CH_REF='$arg'Flt:PFNvoltage-Sts_Ref, CH_FLG='$arg'Flt:PFNvoltage_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Flt:PFNvoltage_MonitFlg-Sts, MODE=1, ENABLED=0")'
    echo 
    echo 'dbLoadRecords("db/MonitBinaryCommon.db", "CH='$arg'Flt:PSUovrheat-Sts, CH_REF='$arg'Flt:PSUovrheat-Sts_Ref, CH_ARCH='$arg'Flt:PSUovrheat_Arch-Sts, CH_FLG='$arg'Flt:PSUovrheat_MonitFlg-Sts, CH_FLGARCH='$arg'Flt:PSUovrheat_ArchFlg-Sts, MODE_PV=BR{}MonitMode-Sel")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Flt:PSUovrheat-Sts, CH_REF='$arg'Flt:PSUovrheat-Sts_Ref, CH_FLG='$arg'Flt:PSUovrheat_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Flt:PSUovrheat_MonitFlg-Sts, MODE=2, ENABLED=1")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Flt:PSUovrheat-Sts, CH_REF='$arg'Flt:PSUovrheat-Sts_Ref, CH_FLG='$arg'Flt:PSUovrheat_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Flt:PSUovrheat_MonitFlg-Sts, MODE=1, ENABLED=0")'
    echo 
    echo 'dbLoadRecords("db/MonitBinaryCommon.db", "CH='$arg'Sts:PSUcircBreaker-Sts, CH_REF='$arg'Sts:PSUcircBreaker-Sts_Ref, CH_ARCH='$arg'Sts:PSUcircBreaker_Arch-Sts, CH_FLG='$arg'Sts:PSUcircBreaker_MonitFlg-Sts, CH_FLGARCH='$arg'Sts:PSUcircBreaker_ArchFlg-Sts, MODE_PV=BR{}MonitMode-Sel")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Sts:PSUcircBreaker-Sts, CH_REF='$arg'Sts:PSUcircBreaker-Sts_Ref, CH_FLG='$arg'Sts:PSUcircBreaker_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Sts:PSUcircBreaker_MonitFlg-Sts, MODE=2, ENABLED=1")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Sts:PSUcircBreaker-Sts, CH_REF='$arg'Sts:PSUcircBreaker-Sts_Ref, CH_FLG='$arg'Sts:PSUcircBreaker_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Sts:PSUcircBreaker_MonitFlg-Sts, MODE=1, ENABLED=0")'
    echo 
    echo 'dbLoadRecords("db/MonitBinaryCommon.db", "CH='$arg'Flt:HVPSovrcurr-Sts, CH_REF='$arg'Flt:HVPSovrcurr-Sts_Ref, CH_ARCH='$arg'Flt:HVPSovrcurr_Arch-Sts, CH_FLG='$arg'Flt:HVPSovrcurr_MonitFlg-Sts, CH_FLGARCH='$arg'Flt:HVPSovrcurr_ArchFlg-Sts, MODE_PV=BR{}MonitMode-Sel")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Flt:HVPSovrcurr-Sts, CH_REF='$arg'Flt:HVPSovrcurr-Sts_Ref, CH_FLG='$arg'Flt:HVPSovrcurr_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Flt:HVPSovrcurr_MonitFlg-Sts, MODE=2, ENABLED=1")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Flt:HVPSovrcurr-Sts, CH_REF='$arg'Flt:HVPSovrcurr-Sts_Ref, CH_FLG='$arg'Flt:HVPSovrcurr_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Flt:HVPSovrcurr_MonitFlg-Sts, MODE=1, ENABLED=0")'
    echo 
    echo 'dbLoadRecords("db/MonitBinaryCommon.db", "CH='$arg'Sts:TrigUnitRdy-Sts, CH_REF='$arg'Sts:TrigUnitRdy-Sts_Ref, CH_ARCH='$arg'Sts:TrigUnitRdy_Arch-Sts, CH_FLG='$arg'Sts:TrigUnitRdy_MonitFlg-Sts, CH_FLGARCH='$arg'Sts:TrigUnitRdy_ArchFlg-Sts, MODE_PV=BR{}MonitMode-Sel")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Sts:TrigUnitRdy-Sts, CH_REF='$arg'Sts:TrigUnitRdy-Sts_Ref, CH_FLG='$arg'Sts:TrigUnitRdy_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Sts:TrigUnitRdy_MonitFlg-Sts, MODE=2, ENABLED=1")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Sts:TrigUnitRdy-Sts, CH_REF='$arg'Sts:TrigUnitRdy-Sts_Ref, CH_FLG='$arg'Sts:TrigUnitRdy_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Sts:TrigUnitRdy_MonitFlg-Sts, MODE=1, ENABLED=0")'
    echo 
    echo 'dbLoadRecords("db/MonitBinaryCommon.db", "CH='$arg'Flt:BiasPS-Sts, CH_REF='$arg'Flt:BiasPS-Sts_Ref, CH_ARCH='$arg'Flt:BiasPS_Arch-Sts, CH_FLG='$arg'Flt:BiasPS_MonitFlg-Sts, CH_FLGARCH='$arg'Flt:BiasPS_ArchFlg-Sts, MODE_PV=BR{}MonitMode-Sel")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Flt:BiasPS-Sts, CH_REF='$arg'Flt:BiasPS-Sts_Ref, CH_FLG='$arg'Flt:BiasPS_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Flt:BiasPS_MonitFlg-Sts, MODE=2, ENABLED=1")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Flt:BiasPS-Sts, CH_REF='$arg'Flt:BiasPS-Sts_Ref, CH_FLG='$arg'Flt:BiasPS_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Flt:BiasPS_MonitFlg-Sts, MODE=1, ENABLED=0")'
    echo 
    echo 'dbLoadRecords("db/MonitBinaryCommon.db", "CH='$arg'Sts:PSUcontactor-Sts, CH_REF='$arg'Sts:PSUcontactor-Sts_Ref, CH_ARCH='$arg'Sts:PSUcontactor_Arch-Sts, CH_FLG='$arg'Sts:PSUcontactor_MonitFlg-Sts, CH_FLGARCH='$arg'Sts:PSUcontactor_ArchFlg-Sts, MODE_PV=BR{}MonitMode-Sel")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Sts:PSUcontactor-Sts, CH_REF='$arg'Sts:PSUcontactor-Sts_Ref, CH_FLG='$arg'Sts:PSUcontactor_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Sts:PSUcontactor_MonitFlg-Sts, MODE=2, ENABLED=1")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Sts:PSUcontactor-Sts, CH_REF='$arg'Sts:PSUcontactor-Sts_Ref, CH_FLG='$arg'Sts:PSUcontactor_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Sts:PSUcontactor_MonitFlg-Sts, MODE=1, ENABLED=0")'
    echo 
#    echo 'dbLoadRecords("db/MonitBinaryCommon.db", "CH='$arg'Sts:RackDoor-Sts, CH_REF='$arg'Sts:RackDoor-Sts_Ref, CH_ARCH='$arg'Sts:RackDoor_Arch-Sts, CH_FLG='$arg'Sts:RackDoor_MonitFlg-Sts, CH_FLGARCH='$arg'Sts:RackDoor_ArchFlg-Sts, MODE_PV=BR{}MonitMode-Sel")'
#    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Sts:RackDoor-Sts, CH_REF='$arg'Sts:RackDoor-Sts_Ref, CH_FLG='$arg'Sts:RackDoor_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Sts:RackDoor_MonitFlg-Sts, MODE=2, ENABLED=1")'
#    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Sts:RackDoor-Sts, CH_REF='$arg'Sts:RackDoor-Sts_Ref, CH_FLG='$arg'Sts:RackDoor_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Sts:RackDoor_MonitFlg-Sts, MODE=1, ENABLED=0")'
#    echo 
    echo 'dbLoadRecords("db/MonitBinaryCommon.db", "CH='$arg'Sts:PulserDoors-Sts, CH_REF='$arg'Sts:PulserDoors-Sts_Ref, CH_ARCH='$arg'Sts:PulserDoors_Arch-Sts, CH_FLG='$arg'Sts:PulserDoors_MonitFlg-Sts, CH_FLGARCH='$arg'Sts:PulserDoors_ArchFlg-Sts, MODE_PV=BR{}MonitMode-Sel")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Sts:PulserDoors-Sts, CH_REF='$arg'Sts:PulserDoors-Sts_Ref, CH_FLG='$arg'Sts:PulserDoors_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Sts:PulserDoors_MonitFlg-Sts, MODE=2, ENABLED=1")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Sts:PulserDoors-Sts, CH_REF='$arg'Sts:PulserDoors-Sts_Ref, CH_FLG='$arg'Sts:PulserDoors_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Sts:PulserDoors_MonitFlg-Sts, MODE=1, ENABLED=0")'    
    echo 
    echo 'dbLoadRecords("db/MonitBinaryCommon.db", "CH='$arg'Sts:PulserCircBreaker-Sts, CH_REF='$arg'Sts:PulserCircBreaker-Sts_Ref, CH_ARCH='$arg'Sts:PulserCircBreaker_Arch-Sts, CH_FLG='$arg'Sts:PulserCircBreaker_MonitFlg-Sts, CH_FLGARCH='$arg'Sts:PulserCircBreaker_ArchFlg-Sts, MODE_PV=BR{}MonitMode-Sel")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Sts:PulserCircBreaker-Sts, CH_REF='$arg'Sts:PulserCircBreaker-Sts_Ref, CH_FLG='$arg'Sts:PulserCircBreaker_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Sts:PulserCircBreaker_MonitFlg-Sts, MODE=2, ENABLED=1")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Sts:PulserCircBreaker-Sts, CH_REF='$arg'Sts:PulserCircBreaker-Sts_Ref, CH_FLG='$arg'Sts:PulserCircBreaker_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Sts:PulserCircBreaker_MonitFlg-Sts, MODE=1, ENABLED=0")'    
    echo 
    echo 'dbLoadRecords("db/MonitBinaryCommon.db", "CH='$arg'Sts:LocalCtrl-Sts, CH_REF='$arg'Sts:LocalCtrl-Sts_Ref, CH_ARCH='$arg'Sts:LocalCtrl_Arch-Sts, CH_FLG='$arg'Sts:LocalCtrl_MonitFlg-Sts, CH_FLGARCH='$arg'Sts:LocalCtrl_ArchFlg-Sts, MODE_PV=BR{}MonitMode-Sel")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Sts:LocalCtrl-Sts, CH_REF='$arg'Sts:LocalCtrl-Sts_Ref, CH_FLG='$arg'Sts:LocalCtrl_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Sts:LocalCtrl_MonitFlg-Sts, MODE=2, ENABLED=1")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Sts:LocalCtrl-Sts, CH_REF='$arg'Sts:LocalCtrl-Sts_Ref, CH_FLG='$arg'Sts:LocalCtrl_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Sts:LocalCtrl_MonitFlg-Sts, MODE=1, ENABLED=0")'    
    echo 
    echo 'dbLoadRecords("db/MonitBinaryCommon.db", "CH='$arg'Sts:EmergButton-Sts, CH_REF='$arg'Sts:EmergButton-Sts_Ref, CH_ARCH='$arg'Sts:EmergButton_Arch-Sts, CH_FLG='$arg'Sts:EmergButton_MonitFlg-Sts, CH_FLGARCH='$arg'Sts:EmergButton_ArchFlg-Sts, MODE_PV=BR{}MonitMode-Sel")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Sts:EmergButton-Sts, CH_REF='$arg'Sts:EmergButton-Sts_Ref, CH_FLG='$arg'Sts:EmergButton_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Sts:EmergButton_MonitFlg-Sts, MODE=2, ENABLED=1")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Sts:EmergButton-Sts, CH_REF='$arg'Sts:EmergButton-Sts_Ref, CH_FLG='$arg'Sts:EmergButton_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Sts:EmergButton_MonitFlg-Sts, MODE=1, ENABLED=0")'    
    echo 
    echo 'dbLoadRecords("db/MonitBinaryCommon.db", "CH='$arg'Sts:ExtInterlock-Sts, CH_REF='$arg'Sts:ExtInterlock-Sts_Ref, CH_ARCH='$arg'Sts:ExtInterlock_Arch-Sts, CH_FLG='$arg'Sts:ExtInterlock_MonitFlg-Sts, CH_FLGARCH='$arg'Sts:ExtInterlock_ArchFlg-Sts, MODE_PV=BR{}MonitMode-Sel")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Sts:ExtInterlock-Sts, CH_REF='$arg'Sts:ExtInterlock-Sts_Ref, CH_FLG='$arg'Sts:ExtInterlock_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Sts:ExtInterlock_MonitFlg-Sts, MODE=2, ENABLED=1")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Sts:ExtInterlock-Sts, CH_REF='$arg'Sts:ExtInterlock-Sts_Ref, CH_FLG='$arg'Sts:ExtInterlock_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Sts:ExtInterlock_MonitFlg-Sts, MODE=1, ENABLED=0")'    
    echo 
    echo 'dbLoadRecords("db/MonitBinaryCommon.db", "CH='$arg'Sts:PulserHVrly-Sts, CH_REF='$arg'Sts:PulserHVrly-Sts_Ref, CH_ARCH='$arg'Sts:PulserHVrly_Arch-Sts, CH_FLG='$arg'Sts:PulserHVrly_MonitFlg-Sts, CH_FLGARCH='$arg'Sts:PulserHVrly_ArchFlg-Sts, MODE_PV=BR{}MonitMode-Sel")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Sts:PulserHVrly-Sts, CH_REF='$arg'Sts:PulserHVrly-Sts_Ref, CH_FLG='$arg'Sts:PulserHVrly_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Sts:PulserHVrly_MonitFlg-Sts, MODE=2, ENABLED=1")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Sts:PulserHVrly-Sts, CH_REF='$arg'Sts:PulserHVrly-Sts_Ref, CH_FLG='$arg'Sts:PulserHVrly_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Sts:PulserHVrly_MonitFlg-Sts, MODE=1, ENABLED=0")'    
    echo 
    echo 'dbLoadRecords("db/MonitBinaryCommon.db", "CH='$arg'Flt:HVPSovrvoltage-Sts, CH_REF='$arg'Flt:HVPSovrvoltage-Sts_Ref, CH_ARCH='$arg'Flt:HVPSovrvoltage_Arch-Sts, CH_FLG='$arg'Flt:HVPSovrvoltage_MonitFlg-Sts, CH_FLGARCH='$arg'Flt:HVPSovrvoltage_ArchFlg-Sts, MODE_PV=BR{}MonitMode-Sel")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Flt:HVPSovrvoltage-Sts, CH_REF='$arg'Flt:HVPSovrvoltage-Sts_Ref, CH_FLG='$arg'Flt:HVPSovrvoltage_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Flt:HVPSovrvoltage_MonitFlg-Sts, MODE=2, ENABLED=1")'
    echo 'dbLoadRecords("db/MonitBinary.db",       "CH='$arg'Flt:HVPSovrvoltage-Sts, CH_REF='$arg'Flt:HVPSovrvoltage-Sts_Ref, CH_FLG='$arg'Flt:HVPSovrvoltage_MonitFlg-Sts, MODE_PV=BR{}MonitMode-Sel, CH_FLG='$arg'Flt:HVPSovrvoltage_MonitFlg-Sts, MODE=1, ENABLED=0")'    
    echo 

    count=$(( $count + 1 ))
done 

echo
echo 'var(PSCDebug, 1)'
echo '#with debug message: var(PSCDebug, 2)'

count=0
while [ $count -le 5 ]
do
  echo
  echo '#Tx socket'
  echo 'createPSC("TxPSC'${numpsc[$count]}'", "br-psc'${numpsc[$count]}'", 7, 0)'
  echo 'epicsThreadSleep 0.1'
  echo '#Tx sim socket'
  echo '#createPSC("TxPSC'${numpsc[$count]}'", "localhost", 8765, 0)'
  echo '#Rx socket'
  echo 'createPSC("RxPSC'${numpsc[$count]}'", "br-psc'${numpsc[$count]}'", 20, 1)'
  echo 'epicsThreadSleep 0.1'
  echo 'setPSCSendBlockSize("TxPSC'${numpsc[$count]}'", 80, 128)'
  count=$(( $count + 1 ))
done

echo
echo '### Misc stuff ###'
echo 'epicsEnvSet("LOCATION","740 ISB RGB 1")'
echo 'dbLoadRecords("db/iocAdminSoft.db", "IOC=BR-CT{IOC:${IOCNAME}}")'
echo 'asSetFilename("/cf-update/acf/default.acf")'

echo
echo '### Save/Restore ###'
echo 'dbLoadRecords("db/save_restoreStatus.db", "P=BR-CT{IOC:${IOCNAME}}")'
echo 'save_restoreSet_status_prefix("BR-CT{IOC:${IOCNAME}}")'
echo 'set_savefile_path("${TOP}/../${IOCNAME}","/as/save")'
echo 'set_requestfile_path("${TOP}/../${IOCNAME}","/as/req")'
echo 'set_pass0_restoreFile("${IOCNAME}.sav")'
echo 'set_pass1_restoreFile("${IOCNAME}_waveforms.sav")'

echo
echo '### Start IOC ###'
echo 'cd ${TOP}/iocBoot/${IOC}'
echo 'iocInit()'
echo
echo '### caPutLog ###'
echo 'caPutLogInit("ioclog.cs.nsls2.local:7004", 1)'
echo
echo '### Channel Finder'
echo 'dbl > ${TOP}/../${IOCNAME}/records.dbl'
echo 'system "cp ${TOP}/../${IOCNAME}/records.dbl /cf-update/${HOSTNAME}.${IOCNAME}.dbl"'
echo
echo '### Save/Restore ###'
echo 'makeAutosaveFileFromDbInfo("${TOP}/../${IOCNAME}/as/req/${IOCNAME}.req", "autosaveFields_pass0")'
echo 'makeAutosaveFileFromDbInfo("${TOP}/../${IOCNAME}/as/req/${IOCNAME}_waveforms.req", "autosaveFields_pass1")'

echo
echo 'create_monitor_set("${IOCNAME}.req", 5 , "")'
echo 'create_monitor_set("${IOCNAME}_waveforms.req", 30 , "")'
echo

